"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { designChallenges, type DesignChallenge } from "@/lib/design-challenges";

export function DesignLibrary() {
  const [track,setTrack] = useState("All tracks");
  return <div className="dashboard page-enter"><div className="page-heading"><div><p className="eyebrow">REQUIREMENTS. DECISIONS. TRADEOFFS.</p><h1>Design with <em>reason.</em></h1><p>Practice system design, database design, and architecture with Socrates. Build a defensible answer one question at a time.</p></div></div><div className="pattern-intro"><p>New to design? Start with “Model a learning platform.” Each exercise explains its vocabulary. You can write plain English, a schema, SQL, or a text diagram.</p><Link prefetch={false} href="/design/learning-schema">Start with data →</Link></div><div className="pattern-filters" role="group" aria-label="Design track">{["All tracks","System design","Database design","Architecture"].map(item=><button key={item} aria-pressed={track===item} onClick={()=>setTrack(item)}>{item}</button>)}</div><div className="native-problems">{designChallenges.filter(item=>track==="All tracks"||item.track===track).map(item=><Link prefetch={false} href={`/design/${item.id}`} className="native-problem" key={item.id}><span>{item.track} / Guided interview</span><h2>{item.title}</h2><p>{item.brief}</p><strong>Think it through →</strong></Link>)}</div></div>;
}

export function DesignWorkspace({challenge}:{challenge:DesignChallenge}) {
  const [answers,setAnswers]=useState<string[]>(challenge.steps.map(()=>""));
  const [step,setStep]=useState(0); const [hint,setHint]=useState(false); const [review,setReview]=useState(false);
  const [status,setStatus]=useState(""); const [finished,setFinished]=useState(false);
  const key=`socratescode:design:v1:${challenge.id}`;
  useEffect(()=>{
    try {const stored=localStorage.getItem(key);if(stored){const parsed:unknown=JSON.parse(stored);if(Array.isArray(parsed)&&parsed.length===challenge.steps.length&&parsed.every(value=>typeof value==="string"&&value.length<=6000)){
      // Restore a draft from external browser storage.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setAnswers(parsed);
    }}}catch{}
  },[key,challenge.steps.length]);
  const current=challenge.steps[step];
  function update(value:string){const next=answers.map((answer,index)=>index===step?value:answer);setAnswers(next);setReview(false);setFinished(false);try{localStorage.setItem(key,JSON.stringify(next));setStatus("Draft saved on this browser. Shared devices can see these drafts.");}catch{setStatus("Browser storage is unavailable. Keep this page open or export your notes.");}}
  function move(index:number){setStep(index);setHint(false);setReview(false);setFinished(false);}
  function download(){const text=`# ${challenge.title}\n\n${challenge.brief}\n\n`+challenge.steps.map((item,index)=>`## ${item.title}\n${item.question}\n\n${answers[index]||"Not answered"}\n`).join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/markdown;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`${challenge.id}-my-reasoning.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="dashboard pattern-lesson page-enter"><Link prefetch={false} href="/design">← Design practice</Link><div className="page-heading"><div><p className="eyebrow">{challenge.track} / SOCRATIC INTERVIEW</p><h1>{challenge.title}</h1><p>{challenge.brief}</p></div></div><section className="product-context"><h2>Start with these assumptions</h2><ul>{challenge.constraints.map(item=><li key={item}>{item}</li>)}</ul><details><summary>Explain the vocabulary</summary><p>{challenge.vocabulary}</p></details></section><nav className="design-stages" aria-label="Design stages">{challenge.steps.map((item,index)=><button key={item.title} aria-current={step===index?"step":undefined} onClick={()=>move(index)}>{index+1}. {item.title}</button>)}</nav><section className="socratic-exercise"><p className="eyebrow">QUESTION {step+1} OF {challenge.steps.length}</p><h2>{current.title}</h2><label className="field">{current.question}<textarea rows={9} maxLength={6000} value={answers[step]} onChange={event=>update(event.target.value)} placeholder="My assumption is… I would choose… because… The tradeoff is…"/></label><p role="status">{status}</p><div className="lesson-actions"><button className="button secondary" onClick={()=>setHint(true)}>Ask Socrates for a nudge</button><button className="button primary" disabled={!answers[step].trim()} onClick={()=>setReview(true)}>Review my reasoning</button></div>{hint&&<p className="lesson-feedback">Socrates asks: {current.hint}</p>}{review&&<div className="reflection-review"><h3>Compare your reasoning</h3><p>This checklist supports self-review. Your written answer is not automatically graded.</p><ul>{current.review.map(item=><li key={item}>{item}</li>)}</ul>{step<challenge.steps.length-1?<button className="button primary" onClick={()=>move(step+1)}>Next question →</button>:<button className="button primary" onClick={()=>setFinished(true)}>Try the interview follow-up</button>}</div>}{finished&&<div className="product-trace"><h3>Say your answer aloud</h3><p>{challenge.followup}</p><p>Explain your assumptions, a failure case, and a tradeoff without reading the checklist. Then revisit the part you could not explain.</p></div>}</section><footer className="pattern-sources"><button className="button secondary" onClick={download}>Export my reasoning as Markdown</button><p>Design drafts stay on this browser, separately from account progress. Export them for your notes or Obsidian vault. No AI solution is generated and no interview-readiness score is claimed.</p><a href={challenge.source.url} target="_blank" rel="noopener noreferrer">Further reading: {challenge.source.title} (opens in a new tab)</a></footer></div>;
}
