"use client";
import { useState } from "react";
import Link from "next/link";
import type { ProductLesson } from "@/lib/product-lessons";

export function PatternLesson({ title, lesson }: { title: string; lesson: ProductLesson }) {
  const [choice, setChoice] = useState<number | null>(null);
  const [checked, setChecked] = useState(false);
  const [frame, setFrame] = useState(-1);
  const [reflection, setReflection] = useState("");
  const [review, setReview] = useState(false);
  const correct = checked && choice === lesson.correct;
  return <div className="dashboard pattern-lesson page-enter">
    <Link prefetch={false} href="/patterns">← All patterns</Link>
    <div className="page-heading"><div><p className="eyebrow">LEARN WITH SOCRATES</p><h1>{title}.<br /><em>Make it make sense.</em></h1><p>Start with an everyday situation. Make a prediction, investigate it, then explain the decision in your own words.</p></div></div>
    <section className="product-context"><span className="eyebrow">WHERE THIS IS USED · {lesson.evidence}</span><h2>{lesson.product}</h2><p>{lesson.use}</p><h3>How it works</h3><p>{lesson.mechanism}</p><h3>The engineering tradeoff</h3><p>{lesson.tradeoff}</p><a href={lesson.source.url} target="_blank" rel="noopener noreferrer">Read the source: {lesson.source.title} ↗<span className="sr-only"> (opens in a new tab)</span></a><small>Source reviewed September 20, 2026. The walkthrough below is an original teaching example.</small></section>
    <section className="socratic-exercise" aria-labelledby="predict-heading"><p className="eyebrow">01 / PREDICT BEFORE YOU LOOK</p><h2 id="predict-heading">A small situation. Your first decision.</h2><p>{lesson.scenario}</p><fieldset><legend>{lesson.question}</legend>{lesson.options.map((option,index)=><label className="lesson-option" key={option}><input type="radio" name="prediction" checked={choice===index} onChange={()=>{setChoice(index);setChecked(false);}}/>{option}</label>)}</fieldset><button className="button primary" disabled={choice===null} onClick={()=>setChecked(true)}>Explore my reasoning</button><p role="status" className="lesson-feedback">{checked&&choice!==null?lesson.feedback[choice]:"There is no penalty for a wrong prediction. It gives us something to investigate."}</p></section>
    <section className="socratic-exercise"><p className="eyebrow">02 / INVESTIGATE THE STATE</p><h2>Follow one decision at a time.</h2><p>You can explore the trace even if your prediction was wrong.</p><div className="product-trace" aria-live="polite"><span>{frame<0?"Ready to begin":`Step ${frame+1} of ${lesson.frames.length}`}</span><p>{frame<0?lesson.scenario:lesson.frames[frame]}</p></div><div className="lesson-actions"><button className="button secondary" disabled={frame<0} onClick={()=>setFrame(value=>value-1)}>Previous step</button><button className="button primary" disabled={frame===lesson.frames.length-1} onClick={()=>setFrame(value=>value+1)}>Next decision</button></div></section>
    <section className="socratic-exercise"><p className="eyebrow">03 / EXPLAIN AND TRANSFER</p><h2>Now change an assumption.</h2><label className="field">{lesson.reflection}<textarea rows={4} maxLength={3000} value={reflection} onChange={event=>{setReflection(event.target.value);setReview(false);}} placeholder="I would first check… because…"/></label><button className="button secondary" disabled={!reflection.trim()} onClick={()=>setReview(true)}>Review my explanation</button>{review&&<div className="reflection-review"><h3>Check your own reasoning</h3><p>This is a self-review, not an AI grade. Did you name the assumption, explain what breaks, and give a concrete example?</p><p><strong>Compare with the engineering constraint:</strong> {lesson.tradeoff}</p><p>{correct?"Your prediction matched the walkthrough.":"Return to your prediction after the trace. What would you change?"}</p></div>}<p className="runner-note">Your explanation stays in this page while it is open. It is not saved to your account.</p><div className="lesson-actions"><Link className="button primary" prefetch={false} href={`/solve/${lesson.practice}`}>Practice a related building block →</Link><Link prefetch={false} href="/design">Explore system design →</Link></div><p>These smaller coding exercises build related skills; they do not reproduce the whole product implementation.</p></section>
  </div>;
}
