import {chromium,expect} from '../../frontend/node_modules/@playwright/test/index.mjs';
import path from 'node:path';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const extension=path.resolve('extension/unpacked');
const output=path.resolve(process.env.TEST_ARTIFACT_DIR||'test-results/extension');mkdirSync(output,{recursive:true});
const context=await chromium.launchPersistentContext('',{channel:'chromium',headless:true,args:['--disable-extensions-except='+extension,'--load-extension='+extension],viewport:{width:390,height:844}});
try {
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');
 const id=new URL(worker.url()).host;
 assert.equal((await worker.evaluate(()=>chrome.sidePanel.getPanelBehavior())).openPanelOnActionClick,true);
 const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(`chrome-extension://${id}/panel.html`);
 await page.getByText('Or paste a problem URL',{exact:true}).click();
 await page.getByLabel('LeetCode problem URL',{exact:true}).fill('https://leetcode.com.evil.test/problems/two-sum/');
 await page.getByRole('button',{name:'Use this problem',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Use an HTTPS LeetCode problem URL');
 await expect(page.locator('#coach')).toBeHidden();
 await page.getByLabel('LeetCode problem URL',{exact:true}).fill('https://leetcode.com/problems/two-sum/?envId=abc');
 await page.getByRole('button',{name:'Use this problem',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Two Sum',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Next thinking step'}).click();
 await expect(page.getByRole('status')).toContainText('Write one idea');
 await page.getByLabel('My reasoning, example or uncertainty',{exact:true}).fill('I need two different indices, not two distinct values.');
 await page.getByRole('button',{name:'Next thinking step'}).click();
 await expect(page.locator('[aria-current=step]')).toHaveText('2. Predict');
 await page.getByLabel('What would you like to think about?',{exact:true}).selectOption('arrays');
 for(let n=0;n<3;n++)await page.getByRole('button',{name:'Ask Socrates for a nudge'}).click();
 await expect(page.getByRole('button',{name:'Ask Socrates for a nudge'})).toBeDisabled();
 await page.getByRole('button',{name:'Save notes',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Saved on this device');
 await page.reload();await page.getByText('Or paste a problem URL',{exact:true}).click();
 await page.getByLabel('LeetCode problem URL',{exact:true}).fill('https://leetcode.com/problems/two-sum/');
 await page.getByRole('button',{name:'Use this problem',exact:true}).click();
 await expect(page.locator('[aria-current=step]')).toHaveText('2. Predict');
 await page.getByRole('button',{name:'1. Understand',exact:true}).click();
 await expect(page.getByLabel('My reasoning, example or uncertainty',{exact:true})).toHaveValue('I need two different indices, not two distinct values.');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export Markdown',exact:true}).click();
 const file=await download;assert.equal(file.suggestedFilename(),'two-sum-socratic-notes.md');
 const stream=await file.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);assert(Buffer.concat(chunks).toString().includes('two different indices'));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'panel fits 390px');
 await page.screenshot({path:path.join(output,'chrome-companion.png'),fullPage:true});
 // Exercise explicit tab capture with a deterministic Chrome API fixture. Actual
 // toolbar permission granting still needs a manual Chrome gesture smoke check.
 await page.evaluate(()=>{chrome.tabs.query=async()=>[{url:'https://leetcode.com/problems/valid-parentheses/',title:'Valid Parentheses - LeetCode'}];});
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Use current LeetCode problem'}).click();
 await expect(page.getByRole('heading',{name:'Valid Parentheses',exact:true})).toBeVisible();
 await expect(page.getByLabel('My reasoning, example or uncertainty',{exact:true})).toHaveValue('');
 await page.evaluate(()=>{chrome.storage.local.set=async()=>{throw new Error('Unavailable');};});
 await page.getByLabel('My reasoning, example or uncertainty',{exact:true}).fill('A close needs an earlier unmatched open.');
 await page.getByRole('button',{name:'Save notes',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Could not save');
 await expect(page.getByLabel('My reasoning, example or uncertainty',{exact:true})).toHaveValue('A close needs an earlier unmatched open.');
 page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:"Delete this problem's notes"}).click();
 await expect(page.getByRole('status')).toContainText('Notes deleted');
 assert.deepEqual(errors,[]);
 console.log('PASS: loaded MV3 extension, real local storage, guidance, URL boundaries, saved context, export, deletion, failure feedback and layout. Toolbar grant needs manual Chrome check.');
} finally {await context.close();}
