import { chromium, firefox, webkit, expect } from "@playwright/test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import path from "node:path";
const baseURL = process.env.WEB_APP_URL || "http://localhost:3001";
if (!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname)) throw new Error("Account tests create test users; use a local or CI test database only.");
const engine = { chromium, firefox, webkit }[process.env.BROWSER || "chromium"];
const browser = await engine.launch({ channel: engine === chromium && process.platform === "win32" ? "msedge" : undefined });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage(); const errors = []; page.on("pageerror", e => errors.push(e.message));
const artifacts = path.resolve(process.env.TEST_ARTIFACT_DIR || "test-results/accounts"); mkdirSync(artifacts, { recursive: true });
const email = `browser-${process.env.E2E_RUN_ID || randomUUID()}-${randomUUID()}@example.test`; const password = `practice-${randomUUID()}`;
try {
  await page.goto(baseURL + "/learn/a-running-total");
  await page.getByRole("button", { name: /Continue to Run/ }).click();
  await page.getByRole("status").filter({hasText:/whole-number prediction/}).waitFor();
  await page.getByLabel("What will total print?").fill("6");
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem("socratescode:lessons:v1")||"{}")["a-running-total"]?.prediction==="6");
  await page.goto(baseURL + "/account");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await page.getByLabel("Your name").fill("Browser Learner");
  await page.getByLabel("Email address").fill(email);
  await page.locator('input[name="password"]').fill(password);
  await page.getByRole("button", { name: "Create my account" }).click();
  await page.getByRole("heading", { name: "Bring your guest work with you." }).waitFor();
  await page.getByRole("button", { name: "Import guest progress" }).click();
  await page.getByText("Guest import complete.", { exact: false }).waitFor();
  await page.getByRole("link", { name: "A running total", exact: true }).click();
  await expect(page.getByLabel("What will total print?")).toHaveValue("6");
  await page.getByLabel("What will total print?").fill("123");
  await page.getByRole("button", { name: "Save to account" }).click();
  await page.getByText("Saved to your account.", { exact: false }).waitFor();
  await page.reload();
  await page.getByRole("button", { name: "Save to account" }).waitFor();
  await expect(page.getByLabel("What will total print?")).toHaveValue("123");
  await page.goto(baseURL + "/account");
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByRole("heading", { name: "Welcome back" }).waitFor();
  await page.goto(baseURL + "/learn/a-running-total");
  await expect(page.getByLabel("What will total print?"), "guest progress is isolated from account edits").toHaveValue("6");
  const other = await browser.newContext(); const device = await other.newPage();
  await device.goto(baseURL + "/account");
  await device.getByLabel("Email address").fill(email);
  await device.getByLabel("Password", { exact: true }).fill(password);
  await device.getByRole("button", { name: "Sign in to my account" }).click();
  await device.getByRole("heading", { name: "Saved to your account" }).waitFor();
  await device.getByRole("link", { name: "A running total", exact: true }).click();
  await expect(device.getByLabel("What will total print?"), "new device loads the database save").toHaveValue("123");
  await other.close();
  await page.goto(baseURL + "/practice");
  await page.getByRole("button", { name: "Reference library", exact: true }).click();
  await expect(page.locator(".practice-card")).toHaveCount(54);
  await page.getByRole("combobox", { name: /^Problem source/ }).selectOption("CSES");
  await expect(page.locator(".practice-card")).toHaveCount(20);
  await page.getByRole("combobox", { name: /^Problem topic/ }).selectOption("Prefix sums");
  await page.getByRole("searchbox", { name: "Search problems" }).fill("range sum");
  await expect(page.locator(".practice-card")).toHaveCount(1);
  assert.equal(await page.locator(".practice-card a").getAttribute("href"), "https://cses.fi/problemset/task/1646");
  await page.locator(".practice-card summary").focus(); await page.keyboard.press("Enter");
  assert.equal(await page.locator(".practice-card details").getAttribute("open"), "");
  for (const width of [320,390,768]) { await page.setViewportSize({width,height:844}); assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `practice overflow at ${width}`); }
  await page.screenshot({ path: path.join(artifacts, "practice-mobile.png") });
  await page.goto(baseURL + "/account");
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(artifacts, "account-mobile.png") });
  assert.deepEqual(errors, []);
  console.log("PASS: real signup, explicit guest import, save, reload, logout, second-device login, guest isolation, practice filters, keyboard and responsive layout");
} catch (error) { await page.screenshot({ path: path.join(artifacts, "failure.png"), fullPage: true }); throw error; }
finally { await browser.close(); }
