import { chromium, firefox, webkit, expect } from "@playwright/test";
import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { codingProblems } from "../lib/coding-problems.ts";
import { foundationLessons } from "../lib/engineering-foundations.ts";
const base = process.env.WEB_APP_URL || "http://localhost:3001";
const engine = {chromium,firefox,webkit}[process.env.BROWSER || "chromium"];
const browser = await engine.launch({channel:engine===chromium&&process.platform==="win32"?"msedge":undefined});
const context = await browser.newContext({viewport:{width:1440,height:1000}});
const page = await context.newPage();
const bypass = process.env.VERCEL_AUTOMATION_BYPASS_SECRET;
if (bypass) {
  const origin = new URL(base);
  if (origin.protocol !== "https:" || !origin.hostname.endsWith(".vercel.app")) throw new Error("Unsupported protected preview host");
  await page.context().route(origin.origin + "/**", route => route.continue({ headers: { ...route.request().headers(), "x-vercel-protection-bypass": bypass } }));
}
const artifacts = path.resolve(process.env.TEST_ARTIFACT_DIR || "test-results/learning"); mkdirSync(artifacts,{recursive:true});
const runtimeLog=[];
page.on("console",message=>{if(message.type()==="error")runtimeLog.push(message.text().slice(0,1500));});
page.on("requestfailed",request=>runtimeLog.push({url:request.url(),failure:request.failure()}));
const errors=[]; page.on("pageerror",error=>errors.push(error.message));
try {
  const foundationsResponse=await page.goto(base+"/foundations");
  const headers=foundationsResponse.headers();
  assert.equal(headers["x-content-type-options"],"nosniff");assert.equal(headers["x-frame-options"],"SAMEORIGIN");assert.equal(headers["x-powered-by"],undefined);
  assert.match(headers["content-security-policy"],/object-src 'none'/);assert.match(headers["permissions-policy"],/camera=\(\)/);
  const runnerProbe=await context.newPage();const runnerResponse=await runnerProbe.goto(base+"/runner");assert.match(runnerResponse.headers()["content-security-policy"],/default-src 'none'/);assert.match(runnerResponse.headers()["content-security-policy"],/sandbox allow-scripts/);await runnerProbe.close();
  const network=[];page.on("request",request=>{if(/https:\/\/(shop|practice)\.test/.test(request.url()))network.push(request.url());});
  for(const lesson of foundationLessons){
    await page.getByRole("navigation",{name:"Engineering lessons"}).getByRole("button",{name:new RegExp(lesson.title)}).click();
    const prediction=page.locator(".foundations-lesson .debug-question").first();
    await prediction.getByRole("radio",{name:lesson.prediction.options[(lesson.prediction.correct+1)%3],exact:true}).check();await prediction.getByRole("button",{name:"Check my reasoning"}).click();
    await expect(page.getByRole("textbox",{name:"Command",exact:true})).toHaveCount(0);
    await prediction.getByRole("radio",{name:lesson.prediction.options[lesson.prediction.correct],exact:true}).check();await prediction.getByRole("button",{name:"Check my reasoning"}).click();
    for(const command of lesson.commands){await page.getByRole("textbox",{name:"Command",exact:true}).fill(command);await page.getByRole("textbox",{name:"Command",exact:true}).press("Enter");}
    await expect(page.locator(".foundation-goal")).toContainText("Practice objective reached");
    const transfer=page.locator(".foundations-lesson .debug-question").nth(1);
    await transfer.getByRole("radio",{name:lesson.transfer.options[(lesson.transfer.correct+1)%3],exact:true}).check();await transfer.getByRole("button",{name:"Check my reasoning"}).click();await expect(page.locator(".foundation-complete")).toHaveCount(0);
    await transfer.getByRole("radio",{name:lesson.transfer.options[lesson.transfer.correct],exact:true}).check();await transfer.getByRole("button",{name:"Check my reasoning"}).click();await expect(page.locator(".foundation-complete")).toBeVisible();
  }
  assert.deepEqual(network,[]);
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"foundations fits mobile");await page.screenshot({path:path.join(artifacts,"foundations-mobile.png"),fullPage:true});
  await page.getByRole("textbox",{name:"Command",exact:true}).fill(`echo '<img src=x onerror=alert(1)>'`);await page.getByRole("textbox",{name:"Command",exact:true}).press("Enter");await expect(page.locator(".terminal-history img")).toHaveCount(0);
  await page.getByRole("button",{name:"Reset this simulation"}).click();await expect(page.locator(".foundation-goal")).toContainText("not reached yet");
  await page.reload();await expect(page.locator(".foundation-storage")).toContainText("5 / 5");
  await page.getByRole("searchbox",{name:"Find a command"}).fill("no-such-command");await expect(page.getByRole("button",{name:"Clear command search"})).toBeVisible();await page.getByRole("button",{name:"Clear command search"}).click();await expect(page.locator(".command-guide article")).toHaveCount(27);
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(base+"/debugging");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.evaluate(()=>localStorage.setItem("socratescode:debugging-method:v1",'{"version":1,"completed":99}'));
  await page.reload();
  await expect(page.getByRole("button",{name:"04 Repair, then challenge it"})).toBeDisabled();
  const methodAnswers = ["A runtime error: an instruction could not finish", "[4, 2]: expected 6, actual 2", "After visiting the second price", "Run the original failing case, empty and single baskets, and a basket ending in a free item"];
  for (let index=0;index<4;index++) {
    if(index===2) {
      await expect(page.locator(".debug-question")).toHaveCount(0);
      await page.getByRole("button",{name:"Next state",exact:true}).click();
      await page.getByRole("button",{name:"Next state",exact:true}).click();
      await expect(page.getByRole("status").filter({hasText:"Mismatch:"})).toContainText("earlier work has been lost");
      await page.getByRole("button",{name:"Next state",exact:true}).click();
      await expect(page.getByRole("button",{name:"Next state",exact:true})).toBeDisabled();
      await page.getByRole("button",{name:"Previous state",exact:true}).click();
      await expect(page.getByRole("status").filter({hasText:"After price = 2"})).toBeVisible();
    }
    const question=page.locator(".debug-question");
    await question.getByRole("radio").nth(index===3?1:0).check();
    await question.getByRole("button",{name:"Check my reasoning"}).click();
    const next=page.getByRole("button",{name:index===3?"Finish and practise":"Save and continue",exact:true});
    await expect(next).toBeDisabled();
    await question.getByRole("radio",{name:methodAnswers[index],exact:true}).check();
    await question.getByRole("button",{name:"Check my reasoning"}).click();
    await next.focus(); await next.press("Enter");
    await page.reload();
    await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
    if(index<3) await expect(page.locator('.beginner-steps [aria-current="step"]')).toContainText(`0${index+2}`);
  }
  await expect(page.getByRole("heading",{name:"Now investigate a real program."})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"debugging method fits mobile");
  await page.getByRole("button",{name:"Review the method"}).click();
  await page.screenshot({path:path.join(artifacts,"debugging-method-mobile.png"),fullPage:true,animations:"disabled"});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(base+"/start");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.evaluate(()=>localStorage.setItem("socratescode:beginner:v1",'{"version":1,"completed":900,"practicePassed":true}'));
  await page.reload();
  await expect(page.getByRole("button",{name:"04 Write it yourself"})).toBeDisabled();
  for (const [index, prediction, transfer] of [[0,"3","1"],[1,"5","3"],[2,"3","Keep the old position and add the current step"]]) {
    const forms=page.locator(".beginner-question");
    await forms.first().getByRole("radio").first().check();
    await forms.first().getByRole("button",{name:"Check my thinking"}).click();
    await expect(page.getByRole("button",{name:"Trace the first line"})).toBeDisabled();
    await forms.first().getByRole("radio",{name:prediction,exact:true}).check();
    await forms.first().getByRole("button",{name:"Check my thinking"}).click();
    await page.getByRole("button",{name:"Trace the first line"}).click();
    const changes=[3,5,4][index];
    for(let n=1;n<changes;n++)await page.getByRole("button",{name:"Trace the next change"}).click();
    await forms.nth(1).getByRole("radio",{name:transfer,exact:true}).check();
    await forms.nth(1).getByRole("button",{name:"Check my thinking"}).click();
    if(index===0)await page.screenshot({path:path.join(artifacts,"beginner-desktop.png"),fullPage:true});
    await page.getByRole("button",{name:index===2?"Open my independent challenge":"Save and continue"}).click();
    await page.reload();
    await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
    await expect(page.locator(".beginner-steps [aria-current=step]")).toContainText(`0${index+2}`);
  }
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"beginner journey fits mobile");
  await page.screenshot({path:path.join(artifacts,"beginner-mobile.png"),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(base+"/patterns");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("searchbox").fill("PostgreSQL");
  await expect(page.locator(".pattern-card")).toHaveCount(2);
  await page.goto(base+"/patterns/sliding-window");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.getByLabel("Keep 2 and add 4",{exact:true}).check();
  await page.getByRole("button",{name:"Explore my reasoning"}).click();
  await page.getByRole("status").filter({hasText:"four minutes"}).waitFor();
  await page.getByLabel("Remove 2 and add 4",{exact:true}).check();
  await page.getByRole("button",{name:"Explore my reasoning"}).click();
  await page.getByRole("status").filter({hasText:"Retain the overlap"}).waitFor();
  for(let n=0;n<3;n++)await page.getByRole("button",{name:"Next decision"}).click();
  await page.getByText("The newest minute arrives",{exact:false}).waitFor();
  assert(await page.getByRole("button",{name:"Next decision"}).isDisabled());
  await page.getByRole("textbox").fill("A late event may change a window we already reported. We need an explicit late-event policy.");
  await page.getByRole("button",{name:"Review my explanation"}).click();
  await page.getByText("This is a self-review",{exact:false}).waitFor();
  await page.goto(base+"/design/learning-schema");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  const answer="I would store learners, versioned problems and attempts, each attempt tied to its exact problem version.";
  await page.getByRole("textbox").fill(answer);
  await page.getByRole("button",{name:"Ask Socrates for a nudge"}).click();
  await page.getByText("Socrates asks:",{exact:false}).waitFor();
  await page.getByRole("button",{name:"Review my reasoning"}).click();
  await page.getByRole("button",{name:"Next question"}).click();
  await page.getByRole("button",{name:"1. Identify entities"}).click();
  assert.equal(await page.getByRole("textbox").inputValue(),answer);
  await page.reload();
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.waitForFunction(text=>document.querySelector("textarea")?.value===text,answer);
  const download=page.waitForEvent("download");await page.getByRole("button",{name:"Export my reasoning as Markdown"}).click();assert.equal((await download).suggestedFilename(),"learning-schema-my-reasoning.md");
  await page.goto(base+"/practice");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await expect(page.locator(".native-problem")).toHaveCount(codingProblems.length);
  await page.goto(base+"/solve/trail-total");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.locator(".monaco-editor").waitFor({timeout:30000});
  await page.getByRole("button",{name:"Use simple editor"}).click();
  const editor=page.getByRole("textbox",{name:"Python solution editor",exact:true});
  const personal=page.getByRole("region",{name:"My regression tests"});
  await personal.getByText("Build my own test cases",{exact:true}).click();
  await personal.getByRole("textbox",{name:"Case name",exact:true}).fill("Two values");
  await personal.getByRole("textbox",{name:"Test input (JSON)",exact:true}).fill("[2,]");
  await personal.getByRole("textbox",{name:"Expected result (JSON)",exact:true}).fill("5");
  await personal.getByRole("button",{name:"Add test case",exact:true}).click();
  await expect(personal.getByRole("status")).toContainText("Input must be small, valid JSON");
  await personal.getByRole("textbox",{name:"Test input (JSON)",exact:true}).fill("[2,3]");
  await personal.getByRole("button",{name:"Add test case",exact:true}).click();
  await personal.getByRole("textbox",{name:"Case name",exact:true}).fill("Empty input");
  await personal.getByRole("textbox",{name:"Test input (JSON)",exact:true}).fill("[]");
  await personal.getByRole("textbox",{name:"Expected result (JSON)",exact:true}).fill("0");
  await personal.getByRole("button",{name:"Add test case",exact:true}).click();
  await editor.fill("def solve(data):\n    return data[-1] if data else 0\n");
  await personal.getByRole("button",{name:"Run my tests",exact:true}).click();
  await page.locator(".run-status").filter({hasText:"Your test run finished"}).waitFor({timeout:75000});
  await expect(page.locator('.case-result[data-passed="true"]')).toHaveCount(1);
  await expect(page.locator('.case-result[data-passed="false"]')).toHaveCount(1);
  await editor.fill("def solve(data):\n    return sum(data)\n");
  await personal.getByRole("button",{name:"Run my tests",exact:true}).click();
  await page.locator(".run-status").filter({hasText:"Your test run finished"}).waitFor({timeout:75000});
  await expect(page.locator('.case-result[data-passed="true"]')).toHaveCount(2);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem("socratescode:beginner:v1")).practicePassed),false,"personal expectations never award platform completion");
  await personal.getByRole("button",{name:"Edit test 1: Two values",exact:true}).click();
  await personal.getByRole("textbox",{name:"Case name",exact:true}).fill("Two signed steps");
  await personal.getByRole("button",{name:"Update test case",exact:true}).click();
  await expect(page.locator('.case-result')).toHaveCount(0);
  await page.reload();
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy","false");
  await page.getByRole("button",{name:"Use simple editor"}).click();
  await personal.getByText("Build my own test cases",{exact:true}).click();
  await expect(personal.getByRole("button",{name:"Edit test 1: Two signed steps",exact:true})).toBeVisible();
  await personal.getByRole("button",{name:"Remove test 2: Empty input",exact:true}).click();
  await expect(personal.locator(".personal-case-list li")).toHaveCount(1);
  await editor.fill("def solve(data):\n    return sum(data)\n");
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"All practice checks passed"}).waitFor({timeout:75000});
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem("socratescode:beginner:v1")).practicePassed),true);
  assert.equal(await page.locator('.case-result[data-passed="true"]').count(),4);
  await editor.fill("def solve(data):\n    return 0\n");
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Some checks need another look"}).waitFor({timeout:75000});
  await editor.fill("def solve(data):\n    while True:\n        pass\n");
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"stopped after five seconds"}).waitFor({timeout:75000});
  await editor.fill("def solve(data):\n    return sum(data)\n");
  await page.reload();
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button",{name:"Use simple editor"}).click();
  assert((await editor.inputValue()).includes("return sum(data)"));
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"All practice checks passed"}).waitFor({timeout:75000});
  // Opaque execution cannot access the application's private API.
  let responses=0; const blockedRequests=[];
  page.on("response",response=>{if(response.url().includes("/api/private-probe"))responses++;});
  page.on("requestfailed",request=>{if(request.url().includes("/api/private-probe"))blockedRequests.push(request.failure()?.errorText);});
  await editor.fill(`import js\ndef solve(data):\n    blocked = False\n    try:\n        request = js.XMLHttpRequest.new()\n        request.open("GET", "${base}/api/private-probe", False)\n        request.send()\n    except Exception:\n        blocked = True\n    return {"origin": str(js.location.origin), "blocked": blocked}\n`);
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Some checks need another look"}).waitFor({timeout:75000});
  assert((await page.locator(".case-result pre").first().textContent()).includes('"null"'));
  assert((await page.locator(".case-result pre").first().textContent()).includes('"blocked":true'));
  assert.equal(responses,0,"private API must never return a response to the runner");
  assert(blockedRequests.length>0 || runtimeLog.some(entry=>typeof entry==="string"&&entry.includes("/api/private-probe")&&/connect-src|Content-Security-Policy/.test(entry)),"CSP must reject the private API request");
  await page.goto(base+"/practice");
  await page.getByRole("button",{name:"Debugging",exact:true}).click();
  await expect(page.locator(".native-problem")).toHaveCount(3);
  for (const task of [
    {slug:"debug-basket-total", prediction:"500", diagnosis:"After the second price", fragment:"total = price", repair:"def solve(data):\n    total = 0\n    for price in data:\n        total = total + price\n    return total\n", cases:4},
    {slug:"debug-temperature-boundary", prediction:"2", diagnosis:"[0]", fragment:"reading >= 0", repair:"def solve(data):\n    count = 0\n    for reading in data:\n        if reading > 0:\n            count = count + 1\n    return count\n", cases:5},
    {slug:"debug-inbox-return", prediction:"1", diagnosis:"The return is inside the loop", fragment:"        return unread", repair:"def solve(data):\n    unread = 0\n    for message in data:\n        if message:\n            unread = unread + 1\n    return unread\n", cases:5},
  ]) {
    await page.goto(base+"/solve/"+task.slug);
    await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
    await page.getByRole("button",{name:"Use simple editor"}).click();
    await expect(editor).toHaveValue(new RegExp(task.fragment.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
    const questions=page.locator(".debug-question");
    await questions.first().getByRole("radio").first().check();
    await questions.first().getByRole("button",{name:"Check my reasoning"}).click();
    await expect(questions).toHaveCount(1);
    await questions.first().getByRole("radio",{name:task.prediction,exact:true}).check();
    await questions.first().getByRole("button",{name:"Check my reasoning"}).click();
    await questions.nth(1).getByRole("radio",{name:task.diagnosis,exact:true}).check();
    await questions.nth(1).getByRole("button",{name:"Check my reasoning"}).click();
    await expect(page.getByRole("link",{name:"Go to my editor"})).toBeVisible();
    await page.getByRole("button",{name:"Run all checks",exact:true}).click();
    await page.locator(".run-status").filter({hasText:"Some checks need another look"}).waitFor({timeout:75000});
    await expect(page.getByRole("region",{name:"Explain your repair"})).toHaveCount(0);
    await editor.fill(task.repair);
    await page.getByRole("button",{name:"Run all checks",exact:true}).click();
    await page.locator(".run-status").filter({hasText:"All practice checks passed"}).waitFor({timeout:75000});
    await expect(page.locator('.case-result[data-passed="true"]')).toHaveCount(task.cases);
    const reflection=page.getByRole("region",{name:"Explain your repair"});
    await reflection.getByRole("textbox").fill("I reproduced the mistake, changed the cause, and tested the boundary and empty cases.");
    await reflection.getByRole("button",{name:"Review my explanation"}).click();
    await expect(reflection.getByRole("status")).toContainText("self-review, not an AI grade");
    if (task.slug === "debug-basket-total") {
      await page.screenshot({path:path.join(artifacts,"debugging-desktop.png"),fullPage:true,animations:"disabled"});
      await page.getByText("Try your own input",{exact:true}).click();
      await page.getByRole("button",{name:"Run custom input",exact:true}).click();
      await page.locator(".run-status").filter({hasText:"Custom run finished"}).waitFor({timeout:75000});
      await expect(reflection).toHaveCount(0);
      await page.getByRole("button",{name:"Run all checks",exact:true}).click();
      await page.locator(".run-status").filter({hasText:"All practice checks passed"}).waitFor({timeout:75000});
      await expect(reflection).toBeVisible();
    }
    await editor.fill(task.repair+"# Changed since the last check\n");
    await expect(reflection).toHaveCount(0);
    await page.reload();
    await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
    await page.getByRole("button",{name:"Use simple editor"}).click();
    await expect(editor).toHaveValue(task.repair+"# Changed since the last check\n");
    if (task.slug === "debug-basket-total") {
      const notebook=page.getByRole("region",{name:"Debugging notebook"});
      await notebook.getByText("My debugging notebook",{exact:true}).click();
      await notebook.getByRole("textbox",{name:/Smallest input/}).fill("[4, 2]");
      await notebook.getByRole("textbox",{name:/Expected behavior/}).fill("6");
      await notebook.getByRole("textbox",{name:/Observed behavior/}).fill("2");
      await notebook.getByRole("textbox",{name:/My hypothesis/}).fill("The old total disappears after the second price.");
      await notebook.getByRole("button",{name:"Save notebook"}).click();
      await expect(notebook.getByRole("status")).toHaveText("Notebook saved on this browser.");
      await page.reload();
      await notebook.getByText("My debugging notebook",{exact:true}).click();
      await expect(notebook.getByRole("textbox",{name:/My hypothesis/})).toHaveValue("The old total disappears after the second price.");
      const exported=page.waitForEvent("download");
      await notebook.getByRole("button",{name:"Export debugging notes"}).click();
      const file=await exported;
      assert.equal(file.suggestedFilename(),"debug-basket-total-debugging-notebook.md");
      const stream=await file.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);
      assert(Buffer.concat(chunks).toString("utf8").includes("    The old total disappears after the second price."));
    }
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`debug exercise fits mobile: ${task.slug}`);
    if (task.slug === "debug-basket-total") await page.screenshot({path:path.join(artifacts,"debugging-mobile.png"),fullPage:true,animations:"disabled"});
    await page.setViewportSize({width:1440,height:1000});
  }
  for (const route of ["/patterns/sliding-window","/design/learning-schema","/solve/exercism-leap"]) {
    await page.goto(base+route);
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow on ${route}`);
  }
  assert((await page.locator(".problem-statement").textContent()).includes("400"),"Leap year rules are present");
  await page.screenshot({path:path.join(artifacts,"coding-mobile.png"),fullPage:true});
  await page.goto(base+"/companion");
  await expect(page.getByRole("link",{name:"Download Chrome companion (.zip)"})).toHaveAttribute("href","/downloads/socratescode-chrome.zip");
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"companion install page fits mobile");
  await page.screenshot({path:path.join(artifacts,"companion-install-mobile.png"),fullPage:true,animations:"disabled"});
  await page.goto(base+"/projects");
  await expect(page.locator(".project-storage")).toContainText("Notes save in this browser");
  await page.screenshot({path:path.join(artifacts,"project-mobile.png"),fullPage:true,animations:"disabled"});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"project brief fits mobile");
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole("radio",{name:"The message text",exact:true}).check();
  await page.getByRole("button",{name:"Check the requirement"}).click();
  await expect(page.getByRole("button",{name:"Next delivery"})).toHaveCount(0);
  await page.getByRole("radio",{name:"The notification ID",exact:true}).check();
  await page.getByRole("button",{name:"Check the requirement"}).click();
  await page.getByRole("textbox",{name:"My implementation plan",exact:true}).fill("Remember seen IDs; preserve first-arrival order.");
  await expect(page.getByRole("region",{name:"Implement the inbox"})).toHaveCount(0);
  for(let i=0;i<3;i++)await page.getByRole("button",{name:"Next delivery",exact:true}).click();
  await expect(page.getByRole("button",{name:"Next delivery",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"Previous delivery",exact:true}).click();
  await expect(page.getByRole("region",{name:"Implement the inbox"})).toBeVisible();
  await page.getByRole("button",{name:"Use simple editor"}).click();
  await editor.fill('def solve(data):\n    return {"items": [], "unread": 0}\n');
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.locator(".run-status").filter({hasText:"Some checks need another look"}).waitFor({timeout:75000});
  await expect(page.getByRole("textbox",{name:"My engineering review",exact:true})).toHaveCount(0);
  const inboxSolution='def solve(data):\n    seen = set()\n    read = set(data["readIds"])\n    items = []\n    for event in data["events"]:\n        if event["id"] not in seen:\n            seen.add(event["id"])\n            items.append({"id": event["id"], "message": event["message"], "read": event["id"] in read})\n    return {"items": items, "unread": sum(not item["read"] for item in items)}\n';
  await editor.fill(inboxSolution);
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.locator(".run-status").filter({hasText:"All practice checks passed"}).waitFor({timeout:75000});
  await expect(page.locator('.case-result[data-passed="true"]')).toHaveCount(6);
  await page.getByRole("textbox",{name:"My engineering review",exact:true}).fill("A set remembers identities; a durable service needs atomic ownership-scoped storage.");
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"project editor and review fit mobile");
  await editor.fill(inboxSolution+"# changed\n");
  await expect(page.getByRole("textbox",{name:"My engineering review",exact:true})).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("textbox",{name:"My implementation plan",exact:true})).toHaveValue("Remember seen IDs; preserve first-arrival order.");
  await expect(page.getByRole("textbox",{name:"My engineering review",exact:true})).toHaveCount(0);
  const projectExport=page.waitForEvent("download");await page.getByRole("button",{name:"Export project notes",exact:true}).click();
  const projectFile=await projectExport;assert.equal(projectFile.suggestedFilename(),"notification-inbox-engineering-notes.md");
  const projectStream=await projectFile.createReadStream();const projectChunks=[];for await(const chunk of projectStream)projectChunks.push(chunk);
  assert(Buffer.concat(projectChunks).toString().includes("atomic ownership-scoped storage"));
  await page.setViewportSize({width:1440,height:1000});
  assert.deepEqual(errors,[]);
  const unavailable=await page.context().newPage();
  await unavailable.addInitScript(()=>{
    const read=Storage.prototype.getItem, write=Storage.prototype.setItem;
    const blocked=key=>key==="socratescode:foundations:v1"||key==="socratescode:beginner:v1"||key==="socratescode:debugging-method:v1"||key.startsWith("socratescode:debug-notebook:")||key.startsWith("socratescode:personal-tests:")||key.startsWith("socratescode:project:");
    Storage.prototype.getItem=function(key){if(blocked(key))throw new DOMException("Blocked","SecurityError");return read.call(this,key);};
    Storage.prototype.setItem=function(key,value){if(blocked(key))throw new DOMException("Blocked","QuotaExceededError");return write.call(this,key,value);};
  });
  await unavailable.goto(base+"/foundations");await expect(unavailable.locator(".foundation-storage")).toContainText("Browser storage is unavailable");
  await unavailable.getByRole("radio",{name:foundationLessons[0].prediction.options[1],exact:true}).check();await unavailable.getByRole("button",{name:"Check my reasoning"}).click();
  for(const command of foundationLessons[0].commands){await unavailable.getByRole("textbox",{name:"Command",exact:true}).fill(command);await unavailable.getByRole("textbox",{name:"Command",exact:true}).press("Enter");}
  await unavailable.locator(".debug-question").nth(1).getByRole("radio",{name:foundationLessons[0].transfer.options[1],exact:true}).check();await unavailable.locator(".debug-question").nth(1).getByRole("button",{name:"Check my reasoning"}).click();await expect(unavailable.locator(".foundation-storage")).toContainText("Could not save");
  await unavailable.goto(base+"/start");
  await expect(unavailable.getByText("Browser storage is unavailable.",{exact:false})).toBeVisible();
  await unavailable.getByRole("radio",{name:"3",exact:true}).check();
  await unavailable.getByRole("button",{name:"Check my thinking"}).click();
  await unavailable.getByRole("button",{name:"Trace the first line"}).click();
  await unavailable.getByRole("button",{name:"Trace the next change"}).click();
  await unavailable.getByRole("button",{name:"Trace the next change"}).click();
  await unavailable.locator(".beginner-question").nth(1).getByRole("radio",{name:"1",exact:true}).check();
  await unavailable.locator(".beginner-question").nth(1).getByRole("button",{name:"Check my thinking"}).click();
  await unavailable.getByRole("button",{name:"Save and continue"}).click();
  await expect(unavailable.locator(".beginner-steps [aria-current=step]")).toContainText("02");
  await unavailable.goto(base+"/debugging");
  await expect(unavailable.getByText("Browser storage is unavailable.",{exact:false})).toBeVisible();
  await unavailable.getByRole("radio",{name:methodAnswers[0],exact:true}).check();
  await unavailable.getByRole("button",{name:"Check my reasoning"}).click();
  await unavailable.getByRole("button",{name:"Save and continue"}).click();
  await expect(unavailable.locator(".beginner-steps [aria-current=step]")).toContainText("02");
  await unavailable.goto(base+"/solve/debug-basket-total");
  const localNotebook=unavailable.getByRole("region",{name:"Debugging notebook"});
  await localNotebook.getByText("My debugging notebook",{exact:true}).click();
  await localNotebook.getByRole("textbox",{name:/My hypothesis/}).fill("I can still record my evidence.");
  await localNotebook.getByRole("button",{name:"Save notebook"}).click();
  await expect(localNotebook.getByRole("status")).toContainText("Could not save");
  await expect(localNotebook.getByRole("textbox",{name:/My hypothesis/})).toHaveValue("I can still record my evidence.");
  const localDownload=unavailable.waitForEvent("download");
  await localNotebook.getByRole("button",{name:"Export debugging notes"}).click();
  assert.equal((await localDownload).suggestedFilename(),"debug-basket-total-debugging-notebook.md");
  const unavailableTests=unavailable.getByRole("region",{name:"My regression tests"});
  await unavailableTests.getByText("Build my own test cases",{exact:true}).click();
  await unavailableTests.getByRole("textbox",{name:"Case name",exact:true}).fill("One item");
  await unavailableTests.getByRole("textbox",{name:"Test input (JSON)",exact:true}).fill("[7]");
  await unavailableTests.getByRole("textbox",{name:"Expected result (JSON)",exact:true}).fill("7");
  await unavailableTests.getByRole("button",{name:"Add test case",exact:true}).click();
  await expect(unavailableTests.getByRole("status")).toContainText("Could not save");
  await expect(unavailableTests.getByRole("button",{name:"Run my tests",exact:true})).toBeEnabled();
  await unavailable.goto(base+"/projects");
  await expect(unavailable.locator(".project-storage")).toContainText("Browser storage is unavailable");
  await unavailable.getByRole("radio",{name:"The notification ID",exact:true}).check();
  await unavailable.getByRole("button",{name:"Check the requirement"}).click();
  await unavailable.getByRole("textbox",{name:"My implementation plan",exact:true}).fill("I can keep working without storage.");
  await expect(unavailable.locator(".project-storage")).toContainText("Could not save");
  await expect(unavailable.getByRole("textbox",{name:"My implementation plan",exact:true})).toHaveValue("I can keep working without storage.");
  await unavailable.close();
  console.log("PASS: Socratic feedback and traces, design drafting/export, editor execution, wrong answer, timeout/recovery, persistence, opaque origin, mobile");
} catch(error) { writeFileSync(path.join(artifacts,"runtime-errors.json"),JSON.stringify(runtimeLog,null,2)); await page.screenshot({path:path.join(artifacts,"learning-failure.png"),fullPage:true});console.error(await page.locator(".run-status").textContent().catch(()=>""));throw error; }
finally {await browser.close();}
