import { chromium, firefox, webkit, expect } from "@playwright/test";
import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
const base = process.env.WEB_APP_URL || "http://localhost:3001";
const engine = {chromium,firefox,webkit}[process.env.BROWSER || "chromium"];
const browser = await engine.launch({channel:engine===chromium&&process.platform==="win32"?"msedge":undefined});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const artifacts = path.resolve(process.env.TEST_ARTIFACT_DIR || "test-results/learning"); mkdirSync(artifacts,{recursive:true});
const runtimeLog=[];
page.on("console",message=>{if(message.type()==="error")runtimeLog.push(message.text().slice(0,1500));});
page.on("requestfailed",request=>runtimeLog.push({url:request.url(),failure:request.failure()}));
const errors=[]; page.on("pageerror",error=>errors.push(error.message));
try {
  await page.goto(base+"/patterns");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("searchbox").fill("PostgreSQL");
  await expect(page.locator(".pattern-card")).toHaveCount(2);
  await page.goto(base+"/patterns/sliding-window");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.getByLabel("Keep 2 and add 4",{exact:true}).check();
  await page.getByRole("button",{name:"Explore my reasoning"}).click();
  await page.getByRole("status").filter({hasText:"four minutes"}).waitFor();
  await page.getByLabel("Remove 2 and add 4",{exact:true}).check();
  await page.getByRole("button",{name:"Explore my reasoning"}).click();
  await page.getByRole("status").filter({hasText:"Retain the overlap"}).waitFor();
  for(let n=0;n<3;n++)await page.getByRole("button",{name:"Next decision"}).click();
  await page.getByText("The newest minute arrives",{exact:false}).waitFor();
  assert(await page.getByRole("button",{name:"Next decision"}).isDisabled());
  await page.getByRole("textbox").fill("A late event may change a window we already reported. We need an explicit late-event policy.");
  await page.getByRole("button",{name:"Review my explanation"}).click();
  await page.getByText("This is a self-review",{exact:false}).waitFor();
  await page.goto(base+"/design/learning-schema");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  const answer="I would store learners, versioned problems and attempts, each attempt tied to its exact problem version.";
  await page.getByRole("textbox").fill(answer);
  await page.getByRole("button",{name:"Ask Socrates for a nudge"}).click();
  await page.getByText("Socrates asks:",{exact:false}).waitFor();
  await page.getByRole("button",{name:"Review my reasoning"}).click();
  await page.getByRole("button",{name:"Next question"}).click();
  await page.getByRole("button",{name:"1. Identify entities"}).click();
  assert.equal(await page.getByRole("textbox").inputValue(),answer);
  await page.reload();
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.waitForFunction(text=>document.querySelector("textarea")?.value===text,answer);
  const download=page.waitForEvent("download");await page.getByRole("button",{name:"Export my reasoning as Markdown"}).click();assert.equal((await download).suggestedFilename(),"learning-schema-my-reasoning.md");
  await page.goto(base+"/practice");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await expect(page.locator(".native-problem")).toHaveCount(20);
  await page.goto(base+"/solve/trail-total");
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.locator(".monaco-editor").waitFor({timeout:30000});
  await page.getByRole("button",{name:"Use simple editor"}).click();
  const editor=page.getByRole("textbox",{name:"Python solution editor",exact:true});
  await editor.fill("def solve(data):\n    return sum(data)\n");
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"All practice checks passed"}).waitFor({timeout:75000});
  assert.equal(await page.locator('.case-result[data-passed="true"]').count(),4);
  await editor.fill("def solve(data):\n    return 0\n");
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Some checks need another look"}).waitFor({timeout:75000});
  await editor.fill("def solve(data):\n    while True:\n        pass\n");
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"stopped after five seconds"}).waitFor({timeout:75000});
  await editor.fill("def solve(data):\n    return sum(data)\n");
  await page.reload();
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");
  await page.getByRole("button",{name:"Use simple editor"}).click();
  assert((await editor.inputValue()).includes("return sum(data)"));
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"All practice checks passed"}).waitFor({timeout:75000});
  // Opaque execution cannot access the application's private API.
  let responses=0; const blockedRequests=[];
  page.on("response",response=>{if(response.url().includes("/api/private-probe"))responses++;});
  page.on("requestfailed",request=>{if(request.url().includes("/api/private-probe"))blockedRequests.push(request.failure()?.errorText);});
  await editor.fill(`import js\ndef solve(data):\n    blocked = False\n    try:\n        request = js.XMLHttpRequest.new()\n        request.open("GET", "${base}/api/private-probe", False)\n        request.send()\n    except Exception:\n        blocked = True\n    return {"origin": str(js.location.origin), "blocked": blocked}\n`);
  await page.getByRole("button",{name:"Run all checks",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Some checks need another look"}).waitFor({timeout:75000});
  assert((await page.locator(".case-result pre").first().textContent()).includes('"null"'));
  assert((await page.locator(".case-result pre").first().textContent()).includes('"blocked":true'));
  assert.equal(responses,0,"private API must never return a response to the runner");
  assert(blockedRequests.length>0 || runtimeLog.some(entry=>typeof entry==="string"&&entry.includes("/api/private-probe")&&/connect-src|Content-Security-Policy/.test(entry)),"CSP must reject the private API request");
  for (const route of ["/patterns/sliding-window","/design/learning-schema","/solve/exercism-leap"]) {
    await page.goto(base+route);
  await expect(page.locator(".guest-profile")).toHaveAttribute("aria-busy", "false");await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow on ${route}`);
  }
  assert((await page.locator(".problem-statement").textContent()).includes("400"),"Leap year rules are present");
  await page.screenshot({path:path.join(artifacts,"coding-mobile.png"),fullPage:true});
  assert.deepEqual(errors,[]);
  console.log("PASS: Socratic feedback and traces, design drafting/export, editor execution, wrong answer, timeout/recovery, persistence, opaque origin, mobile");
} catch(error) { writeFileSync(path.join(artifacts,"runtime-errors.json"),JSON.stringify(runtimeLog,null,2)); await page.screenshot({path:path.join(artifacts,"learning-failure.png"),fullPage:true});console.error(await page.locator(".run-status").textContent().catch(()=>""));throw error; }
finally {await browser.close();}
