import importedProblems from "./data/github-problems.json" with { type: "json" };
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type CodingProblem = {
  slug: string; title: string; topic: string; level: "Foundation" | "Developing";
  description: string; contract: string; constraints: string[]; hints: string[];
  tests: { name: string; input: JsonValue; expected: JsonValue }[];
  source?: { name: string; repository: string; revision: string; url: string; license: string };
};
export const starterCode = "def solve(data):\n    # Read the problem, then explain your approach in code.\n    pass\n";
export const codingProblems: CodingProblem[] = [
  { slug:"trail-total", title:"The trail total", topic:"Accumulators", level:"Foundation", description:"A walker records a signed distance for each segment: forward distances are positive and backward distances are negative. Find their final displacement from the starting point.", contract:"Return one integer: the sum of the integers in data. An empty trail ends at its starting point.", constraints:["data is a list of 0–100 integers.","Each distance is between -1,000 and 1,000."], hints:["What single piece of state describes your position after any prefix of the trail?","What should that state be before taking a step?","Can you process a negative segment with the same update as a positive one?"], tests:[{name:"Mixed directions",input:[4,-2,7],expected:9},{name:"No movement",input:[],expected:0},{name:"Backward trail",input:[-3,-6],expected:-9},{name:"Return to start",input:[8,-8,0],expected:0}] },
  { slug:"count-positive-days", title:"Days above zero", topic:"Conditions", level:"Foundation", description:"A sensor records one integer temperature each day. Count how many days were strictly above zero. A zero reading is not a positive day.", contract:"Return the count of positive integers in data.", constraints:["data contains 0–100 integer readings.","Readings are between -100 and 100."], hints:["What is the difference between counting the readings and adding them?","Should zero pass your condition?","Which counter value describes an empty record?"], tests:[{name:"Mixed readings",input:[-2,0,6,3],expected:2},{name:"Empty record",input:[],expected:0},{name:"All freezing",input:[-1,0,-4],expected:0},{name:"All positive",input:[1,1,2],expected:3}] },
  { slug:"largest-step", title:"The largest step", topic:"Adjacent comparisons", level:"Foundation", description:"An instrument gives a sequence of readings. Find the largest absolute change between consecutive readings. There is no change to measure when fewer than two readings exist.", contract:"Return the largest absolute adjacent difference, or 0 for fewer than two values.", constraints:["data is a list of 0–100 integers.","Each reading is between -1,000 and 1,000."], hints:["How many adjacent pairs are there for n readings?","Should a fall of eight count less than a rise of eight?","Which previous value is needed when the next reading arrives?"], tests:[{name:"Rise and fall",input:[2,8,3],expected:6},{name:"One reading",input:[7],expected:0},{name:"No readings",input:[],expected:0},{name:"Crossing zero",input:[-8,5,4],expected:13}] },
  { slug:"even-contributions", title:"Even contributions", topic:"Filtering", level:"Foundation", description:"A collection contains signed integer contributions. Add only the even contributions, retaining their signs. Odd contributions do not affect the result.", contract:"Return the sum of values divisible by two in data.", constraints:["data is a list of 0–100 integers.","Values may be negative or zero."], hints:["How can a remainder tell you whether a value qualifies?","Are negative multiples of two still even?","What should happen if no value qualifies?"], tests:[{name:"Mixed values",input:[1,2,3,4],expected:6},{name:"Negative values",input:[-6,-3,2],expected:-4},{name:"Only odds",input:[1,3,5],expected:0},{name:"Empty input",input:[],expected:0}] },
  { slug:"first-solo-letter", title:"The first solo letter", topic:"Frequency maps", level:"Developing", description:"A message contains lowercase English letters. Find the first letter that appears exactly once in the entire message, using its original position to break ties.", contract:"data is a string. Return the first unique character, or null (None in Python) when none exists.", constraints:["The string contains 0–200 lowercase English letters."], hints:["Can you know whether a letter is unique before inspecting the whole message?","Which data structure records how often each letter occurs?","Does iterating over counts always preserve the position rule you need?"], tests:[{name:"A solo letter",input:"aabcc",expected:"b"},{name:"Choose the earliest",input:"abac",expected:"b"},{name:"No unique letter",input:"aabb",expected:null},{name:"Empty message",input:"",expected:null}] },
  { slug:"stable-guest-list", title:"The stable guest list", topic:"Sets & order", level:"Foundation", description:"A guest list contains repeated numeric IDs. Produce a list containing each ID once, preserving the order in which IDs first appeared.", contract:"Return a list of unique integers in first-appearance order.", constraints:["data is a list of 0–100 integer IDs.","Do not sort the result."], hints:["What question must you ask before appending an ID?","Do you need the same structure to remember membership and output order?","What makes a second occurrence different from a first?"], tests:[{name:"Repeated visitors",input:[4,2,4,3,2],expected:[4,2,3]},{name:"Already unique",input:[3,1,2],expected:[3,1,2]},{name:"One repeated ID",input:[7,7,7],expected:[7]},{name:"Empty list",input:[],expected:[]}] },
  { slug:"balanced-doors", title:"Balanced doors", topic:"Stack reasoning", level:"Developing", description:"A string describes doors being opened with '(' and closed with ')'. Every close must match a previous unmatched open, and all doors must be closed at the end.", contract:"Return True if the parentheses are balanced, otherwise False.", constraints:["data contains 0–200 characters, each '(' or ')'.","The empty sequence is balanced."], hints:["Can the number of unmatched opens ever be negative in a valid prefix?","Is equal total count sufficient for ')('?","Which condition must hold after the final character?"], tests:[{name:"Nested doors",input:"(()())",expected:true},{name:"Wrong order",input:")(",expected:false},{name:"Still open",input:"(()",expected:false},{name:"Empty sequence",input:"",expected:true}] },
  { slug:"two-ticket-budget", title:"A two-ticket budget", topic:"Hash lookup", level:"Developing", description:"You have prices for individual tickets and an exact budget. Decide whether two different tickets can spend that budget exactly. Equal prices are allowed when they belong to different tickets.", contract:"data has values (a list of prices) and target (the budget). Return a boolean.", constraints:["There are 0–100 ticket prices, each from 0–1,000.","A ticket cannot be used twice."], hints:["For the current price, which complementary price would complete the budget?","When should you record the current ticket so it cannot match itself?","How does [4, 4] differ from [4] for a budget of eight?"], tests:[{name:"Exact pair",input:{values:[2,9,5],target:7},expected:true},{name:"One ticket is not two",input:{values:[4],target:8},expected:false},{name:"Equal prices",input:{values:[4,4],target:8},expected:true},{name:"No pair",input:{values:[1,2,3],target:9},expected:false}] },
  { slug:"unique-message-window", title:"An uninterrupted message", topic:"Sliding window", level:"Developing", description:"Find the longest contiguous part of a lowercase message that has no repeated letters. Return its length rather than the text itself.", contract:"data is a string. Return the maximum length of a substring with distinct characters.", constraints:["The message contains 0–200 lowercase letters."], hints:["When a duplicate appears, which part of the current window becomes invalid?","Can the left boundary move backward?","How do you distinguish a repeat inside the current window from an older occurrence outside it?"], tests:[{name:"A repeated pattern",input:"abcaef",expected:5},{name:"All repeated",input:"aaaa",expected:1},{name:"Old occurrence",input:"abba",expected:2},{name:"Empty message",input:"",expected:0}] },
  { slug:"range-ledger", title:"The range ledger", topic:"Prefix sums", level:"Developing", description:"A ledger records signed amounts. Answer several requests for the sum from index left through index right, including both endpoints.", contract:"data has values and queries. Each query is [left, right]. Return one sum per query in the same order.", constraints:["There are 1–100 values and 0–100 queries.","Indices are zero-based and satisfy 0 <= left <= right < len(values)."], hints:["Which prefix sums contain the interval you want?","What changes for a query whose left endpoint is zero?","Can work done for one query help with the next?"], tests:[{name:"Several ranges",input:{values:[3,-2,5,1],queries:[[0,2],[1,3],[2,2]]},expected:[6,4,5]},{name:"Single value",input:{values:[-4],queries:[[0,0]]},expected:[-4]},{name:"No queries",input:{values:[2,3],queries:[]},expected:[]},{name:"Full ledger",input:{values:[1,2,3],queries:[[0,2]]},expected:[6]}] },
  { slug:"reachable-stations", title:"Reachable stations", topic:"Graph traversal", level:"Developing", description:"Stations are numbered from zero. Each listed connection works in both directions. Starting at station zero, count every distinct station you can reach, including the starting station.", contract:"data has n (the number of stations) and edges (pairs of station IDs). Return the reachable count.", constraints:["1 <= n <= 50; there are at most 100 edges.","Cycles and repeated edges are allowed; count each station once."], hints:["What prevents a cycle from causing endless visits?","When should a station be marked visited?","Does a disconnected station count just because its ID exists?"], tests:[{name:"Disconnected network",input:{n:5,edges:[[0,1],[1,2],[3,4]]},expected:3},{name:"Cycle",input:{n:3,edges:[[0,1],[1,2],[2,0]]},expected:3},{name:"Isolated start",input:{n:4,edges:[[1,2]]},expected:1},{name:"Repeated edge",input:{n:2,edges:[[0,1],[0,1]]},expected:2}] },
  { slug:"fewest-tokens", title:"The fewest tokens", topic:"Dynamic programming", level:"Developing", description:"A machine accepts tokens with specified positive values. You have an unlimited supply of each token. Find the fewest tokens whose values add up exactly to the requested amount.", contract:"data has coins and amount. Return the minimum token count, or -1 if impossible. Amount zero needs zero tokens.", constraints:["coins contains 1–10 positive integers.","0 <= amount <= 100."], hints:["Can choosing the biggest token first miss a better combination?","What smaller amount remains after choosing the last token?","How will you distinguish an unreachable amount from one requiring zero tokens?"], tests:[{name:"Greedy trap",input:{coins:[1,3,4],amount:6},expected:2},{name:"Impossible amount",input:{coins:[2,4],amount:7},expected:-1},{name:"No tokens needed",input:{coins:[3],amount:0},expected:0},{name:"Repeated token",input:{coins:[2,5],amount:10},expected:2}] },
  ...importedProblems.map(problem => ({ ...problem, level: "Foundation" as const })),
];
export function getCodingProblem(slug: string) { return codingProblems.find(problem => problem.slug === slug); }
