export type DesignChallenge = {
  id: string; title: string; track: "System design" | "Database design" | "Architecture";
  brief: string; vocabulary: string; constraints: string[];
  steps: { title: string; question: string; hint: string; review: string[] }[];
  followup: string; source: { title: string; url: string };
};
export const designChallenges: DesignChallenge[] = [
  {id:"short-links",title:"Design a short-link service",track:"System design",brief:"People create short links and share them. Visitors should reliably reach the original destination. Design the smallest useful version before scaling it.",vocabulary:"A key is a unique identifier. A cache keeps a reusable copy of data near the reader. An index helps a database locate rows without scanning every row.",constraints:["Assume 10,000 new links and 1 million redirects per day.","Links must support expiry and owner deletion.","A redirect must never return another owner's private link metadata."],steps:[
    {title:"Clarify",question:"What must creating and opening a link do? Which behavior matters most if the service is partly unavailable?",hint:"Separate the person creating a link from the visitor opening it.",review:["Name the create, resolve and delete operations.","State a redirect latency goal and the meaning of an expired or unknown link."]},
    {title:"Model",question:"What fields and database constraints would you use? Describe the redirect request path.",hint:"Can two original URLs share a short key? What identifies the owner?",review:["Give the short key a unique constraint; handle a collision by trying a new key.","Store destination, owner, creation and expiry fields; authorize ownership on management operations."]},
    {title:"Challenge",question:"If a popular link is cached and then deleted, what should a visitor see?",hint:"A cached copy can outlive the authoritative row.",review:["Choose and explain invalidation or a bounded expiry policy.","Keep redirect validation, abuse controls and cache failure behavior in the design."]},
  ],followup:"Traffic grows to 1,000 redirects a second for one link. Which measurement would justify your next change?",source:{title:"PostgreSQL unique constraints",url:"https://www.postgresql.org/docs/current/ddl-constraints.html"}},
  {id:"notification-delivery",title:"Deliver a notification reliably",track:"System design",brief:"A learner completes a milestone. Their notification should eventually be sent even if the worker restarts. A retry should not send the same notification twice when the provider supports idempotency.",vocabulary:"A queue holds work for later. An acknowledgement tells the broker work was handled. Idempotency means repeating the same operation does not repeat its effect.",constraints:["The application database records the milestone.","Workers and email providers can time out.","Users may opt out before a queued message is delivered."],steps:[
    {title:"Clarify",question:"What does 'sent' mean, and which failures can happen between saving a milestone and sending email?",hint:"Separate stored intent, provider acceptance and inbox delivery.",review:["Avoid promising inbox delivery from a successful provider request.","Include application, broker, worker and provider failures."]},
    {title:"Model",question:"How can you avoid saving the milestone but losing the notification request?",hint:"Can both pieces of durable intent be written in one database transaction?",review:["Consider a transactional outbox, then a publisher that retries safely.","Give each event a stable ID; separate publisher confirmation from consumer acknowledgement."]},
    {title:"Challenge",question:"The provider accepted the email but the worker crashed before recording success. What happens on retry?",hint:"The worker cannot infer failure just because it did not receive a response.",review:["Reuse the provider idempotency key when supported and retain delivery state.","Describe residual duplicate risk if the provider lacks idempotency; bound retries and review opt-out status before sending."]},
  ],followup:"The provider is down for two hours. Explain backlog growth, retry delays, alerts and recovery.",source:{title:"RabbitMQ confirms and acknowledgements",url:"https://www.rabbitmq.com/docs/confirms"}},
  {id:"learning-schema",title:"Model a learning platform",track:"Database design",brief:"A learner attempts versioned problems and keeps progress across devices. Design the tables and constraints before writing an API.",vocabulary:"A primary key identifies a row. A foreign key links it to another table. A unique constraint prevents duplicate combinations. A transaction groups changes that must succeed together.",constraints:["One learner can attempt a problem many times.","A published problem can get a new version.","Progress belongs to one authenticated learner."],steps:[
    {title:"Identify entities",question:"Which things have their own identity? Draw or describe how learners, problems, versions and attempts connect.",hint:"Does editing a statement change what an old attempt answered?",review:["Separate a stable problem identity from immutable published versions.","Associate each attempt with a learner and the exact version used."]},
    {title:"Protect invariants",question:"Which rules belong in database constraints, and which queries need indexes?",hint:"Think about loading one learner's recent attempts and one current progress row.",review:["Use foreign keys for valid references and a learner/problem uniqueness rule for current progress if that is your model.","Choose query-driven indexes; never rely on client-supplied learner IDs for authorization."]},
    {title:"Handle concurrency",question:"Two tabs save different progress at the same time. What should the second save do?",hint:"A revision number can show whether the row changed after a tab read it.",review:["Compare an expected revision atomically and surface a conflict rather than silently losing a change.","Choose explicit merge, refresh or overwrite semantics and explain them to the learner."]},
  ],followup:"A learner asks to delete their account. Explain what is removed, anonymized or retained and why.",source:{title:"PostgreSQL constraints and relationships",url:"https://www.postgresql.org/docs/current/ddl-constraints.html"}},
  {id:"seat-reservations",title:"Prevent a double-booked seat",track:"Database design",brief:"Two people try to buy the final seat at the same moment. Model reservation and payment state so a seat cannot be sold twice.",vocabulary:"Concurrency means operations overlap. A lock coordinates access to shared state. Isolation defines what concurrent transactions can observe.",constraints:["Payment happens outside the database transaction.","Temporary reservations expire.","A payment callback can arrive more than once."],steps:[
    {title:"Define the rule",question:"What exactly must never happen? How do available, held and sold differ?",hint:"A successful payment request is not the same as an available seat.",review:["State an invariant: at most one active owner for a particular seat and event.","Describe allowed state transitions, including expiry and cancellation."]},
    {title:"Race two buyers",question:"Both buyers read 'available'. How do you make only one reservation succeed?",hint:"Checking first and writing later can leave a race.",review:["Use an atomic conditional update or appropriate transaction locking with database enforcement.","Handle the losing request as a normal conflict; keep slow payment calls outside long-held locks."]},
    {title:"Recover",question:"Payment succeeds after the hold expires. What is the recovery path?",hint:"Avoid pretending the external payment and local database share one atomic transaction.",review:["Define whether to reject, reconcile or refund; never assign a seat already sold to someone else.","Deduplicate callbacks and keep an auditable payment state machine."]},
  ],followup:"Show a timeline of two competing requests and name the exact operation that decides the winner.",source:{title:"PostgreSQL transaction isolation",url:"https://www.postgresql.org/docs/current/transaction-iso.html"}},
  {id:"modular-platform",title:"Choose boundaries for a small team",track:"Architecture",brief:"Three engineers are building a learning product with accounts, exercises and progress. Choose boundaries that make change and failure manageable.",vocabulary:"A module is an internal boundary. A service is deployed and operated separately. A contract states what a boundary accepts and returns.",constraints:["The team has limited operational capacity.","Accounts and progress require reliable data ownership.","The product may later need independently scaled code execution."],steps:[
    {title:"Find responsibilities",question:"What belongs together, and which component owns each kind of data?",hint:"Start from responsibilities rather than a list of popular technologies.",review:["Separate identity, learning content and learner progress responsibilities.","Name one authoritative writer per data model and define interfaces between modules."]},
    {title:"Choose deployment",question:"Would you begin with a modular monolith or separate services? Defend the choice using these constraints.",hint:"A network boundary introduces latency, failures and operational work.",review:["A well-structured monolith is a valid starting point; separate services need a concrete isolation or scaling reason.","Discuss deployment, testing, observability and cross-boundary transactions rather than counting services."]},
    {title:"Evolve safely",question:"Code execution becomes expensive and unreliable. Where would you isolate it?",hint:"Running learner programs has a different trust and resource profile from saving progress.",review:["Put untrusted execution behind a bounded interface with isolation, deadlines and admission limits.","Keep runners unable to write primary account data and define failure responses before extraction."]},
  ],followup:"What evidence would make you reverse your initial architecture decision?",source:{title:"Martin Fowler: microservice tradeoffs",url:"https://martinfowler.com/articles/microservice-trade-offs.html"}},
  {id:"cache-boundaries",title:"Keep a cache from becoming the authority",track:"Architecture",brief:"A dashboard reads frequently changing progress. Introduce caching only where its staleness and failure behavior are acceptable.",vocabulary:"The source of truth is the authoritative record. TTL means time to live. Invalidation removes a cached value that is no longer trustworthy.",constraints:["Private progress is visible only to its owner.","A save should not appear to vanish on the next read.","The cache can be unavailable while the database remains healthy."],steps:[
    {title:"Measure first",question:"Which query is slow, how often does it run, and how stale may its response be?",hint:"Caching without a latency or load problem adds another consistency problem.",review:["Define measured latency, access frequency and a permitted staleness window.","Consider an index or query improvement before adding another service."]},
    {title:"Protect ownership",question:"What goes into the cache key, and when do you authorize access?",hint:"A problem ID alone does not distinguish different learners' progress.",review:["Include user scope and relevant content version; authorize before returning private cached data.","Never allow a cache hit to bypass account ownership checks."]},
    {title:"Handle failure",question:"What happens if cache invalidation fails after a successful database save?",hint:"The database transaction can commit while a separate cache call fails.",review:["State a bounded staleness or versioning policy and a read-after-write strategy.","Choose fallback and overload limits; a lock does not automatically solve every cache consistency failure."]},
  ],followup:"A popular key expires and thousands of requests miss together. How do you protect the database?",source:{title:"Redis: distributed coordination assumptions",url:"https://redis.io/docs/latest/develop/clients/patterns/distributed-locks/"}},
];
