import type { BeginnerQuestion } from "./beginner.ts";
export type FoundationLesson={id:string;title:string;idea:string;vocabulary:string;prediction:BeginnerQuestion;task:string;commands:string[];hints:string[];transfer:BeginnerQuestion;source:{title:string;url:string}};
export const foundationLessons:FoundationLesson[]=[
  {id:"files",title:"Find your bearings",idea:"The terminal is a text interface. A shell such as Bash interprets commands; commands are instructions, not magic. Start by observing where you are and what exists.",vocabulary:"A directory is a folder. pwd prints the working directory, ls lists entries, and cd changes that directory. A relative path starts at your current directory; an absolute path starts at /. These examples use Unix-style paths. PowerShell is a different shell; Bash examples apply in Bash environments such as Linux, WSL or Git Bash.",
    prediction:{prompt:"You run ls. What changes?",options:["The working directory changes","You see directory entries; the working directory stays the same","Files are moved into a new folder"],correct:1,feedback:["Listing is an observation. Which command's name means change directory?","Correct. Inspecting names does not move you or the files.","Listing does not move files. Watch the prompt's path."]},
    task:"Enter the logs directory, confirm its location with pwd, then display only the lines containing ERROR from app.log.",commands:["pwd","ls","cd logs","pwd","cat app.log","grep -F ERROR app.log"],hints:["Where will a relative filename be looked up?","grep -F matches literal text. It prints matching lines; it does not edit the file."],
    transfer:{prompt:"From /workspace/project/logs, what does cd .. mean?",options:["Delete the logs directory","Move to /workspace/project","Reconnect to a server"],correct:1,feedback:["cd changes location; it does not delete anything.","Yes. .. names the parent directory.","Changing a directory is local to the current shell session."]},source:{title:"GNU Bash: what is a shell?",url:"https://www.gnu.org/software/bash/manual/html_node/What-is-a-shell_003f.html"}},
  {id:"pipes",title:"Follow the output",idea:"An engineer narrows a large amount of evidence into a useful question. Connect small commands to count error lines without changing the log.",vocabulary:"Standard output is a command's ordinary output stream. A pipe, |, sends it to the next command's standard input. wc -l counts newline characters. Exit status 0 usually means success; grep uses 1 for no matches. By default, a Bash pipeline reports its last command's status, so a successful count alone does not prove every earlier command succeeded.",
    prediction:{prompt:"What does grep -F ERROR logs/app.log | wc -l send into wc?",options:["The whole filesystem","The filename only","The matching log lines"],correct:2,feedback:["A pipe connects output streams, not filesystems.","grep prints selected lines. The filename is one of its inputs.","Correct. wc counts the newline-terminated matching lines."]},
    task:"Use a read-only pipeline to count the two error lines in logs/app.log.",commands:["cat logs/app.log","grep -F ERROR logs/app.log | wc -l","cat logs/app.log | grep -F ERROR | wc -l"],hints:["What would you inspect if the count were unexpectedly zero?","A pipe transforms output; redirection with > writes to a file instead."],
    transfer:{prompt:"Your pipeline prints 0. What should you check before concluding the service is healthy?",options:["Whether the source file and filter are correct, including earlier command errors","Nothing; zero proves there were no failures","Delete the log and run again"],correct:0,feedback:["Yes. Missing or incorrectly filtered evidence can look like no errors.","The conclusion depends on the input and filter being right.","Deleting evidence prevents investigation."]},source:{title:"GNU Bash: pipelines",url:"https://www.gnu.org/software/bash/manual/html_node/Pipelines.html"}},
  {id:"git",title:"Know what you commit",idea:"Git records selected versions of files. Understanding the working tree, staging area and commits helps you review a change before sharing it.",vocabulary:"The working tree is your editable files. git add copies a file's current contents into the staging area (index). git commit records the staged snapshot locally. Later edits are not automatically restaged. A commit is not a push to GitHub. This fixture starts with an existing repository and configured fictional author; no init or identity setup is needed.",
    prediction:{prompt:"You stage a file, then edit it again. What will git commit record?",options:["The newest unstaged edit","The version captured when you staged it","Every file on your computer"],correct:1,feedback:["A later edit stays in the working tree until staged again.","Correct. The staging area chooses the next snapshot.","Only staged repository changes belong to this commit."]},
    task:"Write a note, stage it, then change it again. Inspect the staged diff, commit the staged version, and use git status to see the remaining unstaged edit.",commands:['echo "First observation" > notes.txt',"git add notes.txt",'echo "A later observation" > notes.txt',"git diff --staged",'git commit -m "Record first observation"',"git status","git diff","git log --oneline"],hints:["What differs between git diff and git diff --staged?","If the commit includes the later edit, did you run git add again? Reset and compare the two snapshots."],
    transfer:{prompt:"After this local commit, has GitHub received it?",options:["Yes, commit always uploads changes","No; sharing requires a configured remote and a separate push","Only if the commit message is long"],correct:1,feedback:["Recording locally and transmitting to a remote are separate actions.","Yes. A push is a separate action with remote permissions.","Message length does not send data to a remote."]},source:{title:"Git: staging files",url:"https://git-scm.com/docs/git-add"}},
  {id:"ssh",title:"Know which machine",idea:"SSH can open an encrypted remote session. You must know which host you are using, verify its identity, and have permission to access it.",vocabulary:"In ssh user@host, user is the remote account and host identifies the destination. A public key may be installed for authentication; keep its private key private. Verify a new host fingerprint through a trusted channel before accepting it. This exercise assumes that verification has already happened for the fictional host; it does not simulate a real SSH handshake.",
    prediction:{prompt:"After connecting with SSH, where does pwd run?",options:["Always on your laptop","Inside the remote session","On every computer on the network"],correct:1,feedback:["The active session has changed. Check the prompt and host.","Yes. Commands in that session execute on the remote host.","SSH does not broadcast commands to other computers."]},
    task:"Connect to the fictional practice host, inspect its location and error log, exit, then confirm your local location with pwd.",commands:["ssh learner@practice.test","hostname","pwd","grep -F ERROR logs/app.log","exit","pwd"],hints:["The prompt should change from learner@local to learner@practice.test.","exit closes this simulated remote session. It does not delete either machine's files."],
    transfer:{prompt:"A host-key warning unexpectedly says the server identity changed. What should you do?",options:["Disable host-key checking","Share your private key in chat","Stop and verify the change through a trusted administrator or channel"],correct:2,feedback:["Removing identity checks can hide the problem.","A private key is a credential; never share it to resolve a warning.","Correct. Investigate before trusting the changed identity."]},source:{title:"OpenSSH: ssh manual",url:"https://man.openbsd.org/ssh"}},
  {id:"security",title:"Protect the business rule",idea:"A correct calculation is not enough. A shop must check who owns an order, validate quantities against stock, and calculate prices from trusted data. A hidden button is not authorization.",vocabulary:"Authentication identifies the caller; authorization decides what that caller may do. A business invariant is a rule that must remain true, such as a positive quantity within stock. The simulated caller is learner. HTTP 403 means forbidden; 400 means invalid input. curl -i includes response headers. HTTP errors do not automatically produce a nonzero curl exit status without failure options.",
    prediction:{prompt:"A signed-in customer changes an order ID in a request. What must the server check?",options:["Only that the customer is signed in","That this customer may access this particular order","That the URL looks complicated"],correct:1,feedback:["A valid session does not grant access to another customer's data.","Yes. Check access to each requested object on the server.","Unpredictable IDs do not replace authorization."]},
    task:"Read your own order, try the other customer's order, submit a fake client price, and test a negative quantity. Observe the responses rather than treating every request as permitted.",commands:["curl -i https://shop.test/orders/mine","curl -i https://shop.test/orders/someone-else",`curl -i -X POST https://shop.test/checkout -d '{"quantity":1,"unitPrice":1}'`,`curl -i -X POST https://shop.test/checkout -d '{"quantity":-1}'`],hints:["Does the server use the price sent by the caller, or its own catalog?","A real checkout also needs atomic stock updates and a retry/idempotency policy; this fixture models neither."],
    transfer:{prompt:"Two customers each request the final item at the same time. Is checking stock in each browser sufficient?",options:["Yes; both browsers showed one item","No; the server needs an atomic stock rule or reservation when accepting orders","Yes; a stronger CSS rule fixes it"],correct:1,feedback:["Both clients can observe the same old stock value.","Correct. Concurrency is part of the business rule, not just the interface.","Presentation cannot enforce inventory consistency."]},source:{title:"OWASP: object-level authorization",url:"https://owasp.org/www-project-api-security/editions/2023/en/0xa1-broken-object-level-authorization/"}},
];
export const commandGuide=[
  ["pwd","Print your current directory."],["ls -a","List directory entries, including names starting with a dot."],["cd ..","Change to the parent directory."],["cat notes.txt","Print a small text file."],["grep -F ERROR logs/app.log","Print lines containing this literal text."],["head -n 10 logs/app.log","Show the first ten lines; reference only here."],["tail -n 20 logs/app.log","Show the last twenty lines; reference only here."],["wc -l notes.txt","Count newline characters in a file."],["echo 'a note' > notes.txt","Replace a file with this line; > overwrites existing content."],["mkdir practice","Create a directory; reference only here."],["cp source.txt copy.txt","Copy a file; an existing destination may be overwritten. Reference only here."],["mv draft.txt reviewed.txt","Move or rename; check the destination first. Reference only here."],["rm scratch.txt","Remove a file; usually no recycle bin. Reference only here."],["chmod u+x script.sh","Add execute permission for the owner; only run scripts you understand. Reference only here."],["ps","Inspect processes; reference only here."],["curl -I https://example.com","Request HTTP response headers using HEAD; reference only here."],["git status","Inspect staged and unstaged changes."],["git diff","Compare working-tree changes against the staging area."],["git diff --staged","Compare the staged snapshot against the last commit."],["git add notes.txt","Stage this file's current contents."],["git commit -m 'Explain why'","Record a local staged snapshot."],["git log --oneline","Read concise commit history."],["git fetch","Download remote objects and references without integrating them into your branch; reference only here."],["git pull","Fetch and integrate according to options/configuration; inspect your branch first. Reference only here."],["git push","Send local references and associated objects to a remote; reference only here."],["ssh learner@practice.test","Open the fictional remote session in this lab; real SSH requires a permitted host and verified identity."],["exit","Leave the current simulated remote session."],
] as const;
export function parseFoundationProgress(raw:string|null):string[] {
  if(!raw||raw.length>1000)return [];
  try {const parsed:unknown=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))return [];const data=parsed as Record<string,unknown>;if(data.version!==1||!Array.isArray(data.completed)||data.completed.length>foundationLessons.length||!data.completed.every((id:unknown)=>typeof id==="string"&&foundationLessons.some(l=>l.id===id)))return [];return [...new Set<string>(data.completed)];}catch{return [];}
}
