export type ProductLesson = {
  id: string; product: string; evidence: "Documented implementation" | "Illustrative product design";
  use: string; mechanism: string; tradeoff: string;
  source: { title: string; url: string }; scenario: string; frames: string[];
  question: string; options: string[]; correct: number; feedback: string[];
  reflection: string; practice: string;
};
// Sources reviewed 2026-09-20. Scenarios and questions are original teaching examples.
export const productLessons: ProductLesson[] = [
  {
    id: "two-pointers", product: "PostgreSQL: matching database rows", evidence: "Documented implementation",
    use: "A shop needs to connect orders to customer records. PostgreSQL's merge join compares two inputs ordered by their join keys.",
    mechanism: "Keep a position in each sorted input. Advance the smaller key; equal keys can produce matches. This avoids checking every possible pair.",
    tradeoff: "Sorting has a cost. Duplicate keys need extra handling, and another join strategy may be cheaper for a different query.",
    source: {title:"PostgreSQL executor: merge joins",url:"https://www.postgresql.org/docs/17/executor.html"},
    scenario:"Two sorted lists of unique customer IDs are [2, 5, 9] and [1, 5, 8]. Find IDs appearing in both.",
    frames:["Compare 2 with 1. Advance the second list: no later ID in the first list can equal 1.","Compare 2 with 5. Advance the first list.","Compare 5 with 5. Record the match, then advance both.","Compare 9 with 8. Advance the second list; it ends. The shared ID is 5."],
    question:"At the first comparison, which ID can we safely leave behind?",options:["2 in the first list","1 in the second list","Both IDs"],correct:1,
    feedback:["The second list may still contain 2. What can its future values be?","Yes. Every remaining ID in the first list is at least 2, so 1 cannot match.","Advancing both could skip a future match for 2."],
    reflection:"Why does this decision stop being safe if the lists are not sorted?",practice:"two-ticket-budget",
  },
  {
    id:"sliding-window",product:"Apache Flink: rolling stream metrics",evidence:"Documented implementation",
    use:"Flink supports overlapping time windows, useful when a dashboard needs a fresh view of recent events.",
    mechanism:"A window defines which events belong to a calculation. A ten-minute window sliding every minute overlaps nine minutes with the previous one.",
    tradeoff:"Event-time processing must handle late arrivals. Window storage and aggregation cost depend on the operation; not every aggregate supports a simple subtraction.",
    source:{title:"Flink window operators",url:"https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/dev/datastream/operators/windows/"},
    scenario:"A small dashboard counts requests in the last three complete minutes. Counts are [2, 5, 1, 4].",
    frames:["The first window contains 2, 5, 1. Its total is 8.","The oldest minute leaves: subtract 2. The remaining total is 6.","The newest minute arrives: add 4. The new window [5, 1, 4] totals 10."],
    question:"What changes when the three-minute window moves one minute?",options:["Keep 2 and add 4","Remove 2 and add 4","Start the total at zero permanently"],correct:1,
    feedback:["That would count four minutes. Which minute has expired?","Yes. Retain the overlap; only the outgoing and incoming minutes change.","Could you reuse the two minutes that still belong to the window?"],
    reflection:"What would you do if a request from an earlier minute arrived late?",practice:"unique-message-window",
  },
  {
    id:"fast-slow-pointers",product:"A chain of workflow redirects",evidence:"Illustrative product design",
    use:"Imagine validating a configuration where each step redirects to at most one next step. A loop would prevent the workflow from finishing.",
    mechanism:"Walk the same chain at one and two links per turn. Meeting again means a cycle; reaching an end means the chain terminates.",
    tradeoff:"This model requires a deterministic next step. A branching dependency graph needs a graph algorithm. A visited set costs more memory but gives a clearer debugging trail.",
    source:{title:"SymPy: cycle detection in iterated functions",url:"https://docs.sympy.org/latest/modules/ntheory.html"},
    scenario:"The redirects are A → B → C → B. Start both walkers at A and compare them only after moving.",
    frames:["First turn: slow reaches B; fast takes two links and reaches C.","Second turn: slow reaches C; fast follows C → B → C.","They meet at C. Following the redirects would repeat forever."],
    question:"What does the meeting after movement tell us?",options:["C is the final step","The chain contains a cycle","Every workflow is invalid"],correct:1,
    feedback:["C redirects to B, so it is not an end.","Yes. Both walkers remain inside the repeating chain.","The observation applies to this reachable chain, not every configuration."],
    reflection:"How would you show the exact offending cycle to the person editing the workflow?",practice:"reachable-stations",
  },
  {
    id:"cyclic-sort",product:"Checking a numbered import batch",evidence:"Illustrative product design",
    use:"A small import expects unique slot IDs from 1 through n. Putting each ID in its own slot can expose duplicate or missing entries.",
    mechanism:"For valid ID x, the target slot is x − 1. Swap toward that slot and stop when a duplicate already occupies it.",
    tradeoff:"The input is mutated and IDs must be bounded. This is a constrained placement technique, not a general database sorting strategy. A set is often easier to maintain.",
    source:{title:"Python sets: an alternative membership structure",url:"https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset"},
    scenario:"The batch IDs are [3, 1, 2]. Slots are numbered 1, 2, 3.",
    frames:["ID 3 is in slot 1. Its home is slot 3.","Swap slots 1 and 3: [2, 1, 3]. ID 3 is now home.","Put ID 2 in slot 2: [1, 2, 3]. Every slot agrees with its ID."],
    question:"Where does ID 3 belong in a zero-indexed list?",options:["Index 3","Index 0","Index 2"],correct:2,
    feedback:["A three-item list ends at index 2. How does a slot number differ from an index?","Index 0 is the home of ID 1.","Yes. Subtract one from the ID to get its index."],
    reflection:"What validation must happen before using an imported ID as an array index?",practice:"stable-guest-list",
  },
  {
    id:"bitwise-xor",product:"Linux RAID: storage parity",evidence:"Documented implementation",
    use:"Linux RAID-5 documentation describes XOR across stripe data when computing partial parity.",
    mechanism:"XOR combines bits and cancels a value when applied twice. With one missing data block and valid parity, the other blocks can reconstruct it.",
    tradeoff:"A single XOR parity equation cannot recover two unknown blocks. Real storage also needs consistent writes and corruption handling; parity is not encryption.",
    source:{title:"Linux RAID-5 partial parity log",url:"https://www.kernel.org/doc/html/v6.1/driver-api/md/raid5-ppl.html"},
    scenario:"Two tiny blocks contain 6 and 3. Their XOR parity is 5. The block containing 3 becomes unavailable.",
    frames:["In binary: 110 XOR 011 = 101. Store parity 5.","The surviving block is 6 and parity is 5.","Compute 101 XOR 110 = 011. The missing value is 3."],
    question:"Which calculation recovers the missing block?",options:["5 + 6","5 XOR 6","6 − 5"],correct:1,
    feedback:["Addition does not cancel the surviving bits.","Yes. (6 XOR 3) XOR 6 leaves 3.","Subtraction is not the operation used to construct this parity."],
    reflection:"Why is one parity value insufficient when both original blocks are missing?",practice:"exercism-hamming",
  },
  {
    id:"binary-search",product:"Git bisect: finding a regression",evidence:"Documented implementation",
    use:"Git bisect narrows the commits between a known working revision and a broken one by asking you to test selected revisions.",
    mechanism:"Each reliable good/bad result excludes part of the remaining history. A linear history makes the familiar halfway-search example easy to see.",
    tradeoff:"Flaky tests or a bug that appears and disappears undermine the classification. Git history can branch, so real revision selection is more involved than indexing an array.",
    source:{title:"Git bisect manual",url:"https://git-scm.com/docs/git-bisect"},
    scenario:"In a linear history numbered 1–8, commit 1 works and commit 8 fails. Assume one transition from working to broken.",
    frames:["Test commit 4. It works, so the first broken commit must be after 4.","Test commit 6. It fails, leaving commits 5 or 6.","Test commit 5. It works. Commit 6 is the first broken revision."],
    question:"If commit 4 works, where can the first broken commit be?",options:["Only before 4","After 4","Anywhere, even commit 1"],correct:1,
    feedback:["Our assumption says earlier working revisions stay in the working region.","Yes. Keep the failing endpoint and move the working endpoint forward.","That ignores the known working endpoint and the single-transition assumption."],
    reflection:"How would a flaky test affect your confidence in this result?",practice:"largest-step",
  },
  {
    id:"breadth-first-search",product:"Neo4j: shortest paths by hop count",evidence:"Documented implementation",
    use:"Neo4j documents bidirectional breadth-first search for eligible shortest-path queries. The goal is the fewest relationships between nodes.",
    mechanism:"BFS explores neighbors in layers. Every node at distance one is considered before distance two, so the first discovery gives a shortest unweighted distance.",
    tradeoff:"Hop count is not travel time. Weighted routes need a suitable weighted algorithm. Neo4j query predicates can change the search plan.",
    source:{title:"Neo4j shortest-path planning",url:"https://neo4j.com/docs/cypher-manual/4.4/execution-plans/shortestpath-planning/"},
    scenario:"Stations connect A–B, A–C, B–D and C–D. Each connection counts as one hop.",
    frames:["Start with A at distance 0. Mark it visited.","Visit B and C at distance 1 and add their unvisited neighbors.","Discover D at distance 2. A → B → D and A → C → D are equally short."],
    question:"Why do we examine both B and C before going deeper?",options:["To finish the current distance layer","Because their names are alphabetical","Because all routes take the same time"],correct:0,
    feedback:["Yes. The layer order is what makes the hop-count guarantee possible.","Names do not determine distance.","The model counts edges; it says nothing about travel times."],
    reflection:"Which assumption breaks if one connection takes an hour and another takes a minute?",practice:"reachable-stations",
  },
  {
    id:"depth-first-search",product:"Neo4j: exploring a connected graph",evidence:"Documented implementation",
    use:"Neo4j Graph Data Science exposes DFS to traverse a graph by following a branch before backtracking.",
    mechanism:"A stack remembers unfinished branches. Track visited nodes to avoid repeatedly exploring cycles.",
    tradeoff:"DFS does not guarantee a shortest path. Deep recursion can exhaust the call stack; an explicit stack gives more control.",
    source:{title:"Neo4j depth-first search",url:"https://neo4j.com/docs/graph-data-science/current/algorithms/dfs/"},
    scenario:"A component graph has A → B, A → C and B → D. Explore B before C.",
    frames:["Start at A; remember that C still needs a visit.","Follow B, then D. D has no new neighbors.","Backtrack to the unfinished branch and visit C. Order: A, B, D, C."],
    question:"After finishing D, what lets us continue to C?",options:["Sorting every node","Remembering unfinished branches","Assuming D connects to C"],correct:1,
    feedback:["Sorting is unrelated to retaining traversal state.","Yes. The stack or recursive calls remember where exploration remains.","That edge is absent from the graph."],
    reflection:"What would happen without a visited set if D pointed back to A?",practice:"reachable-stations",
  },
  {
    id:"merge-intervals",product:"PostgreSQL: combining occupied time ranges",evidence:"Documented implementation",
    use:"PostgreSQL's range_agg computes the union of ranges. A calendar can use a union to summarize occupied periods.",
    mechanism:"In a teaching implementation, sort by start time. Extend the current interval when the next one overlaps; otherwise start a new interval.",
    tradeoff:"A union loses individual booking identities. Define inclusive/exclusive endpoints and whether touching intervals should be combined. This walkthrough does not claim PostgreSQL uses this exact loop.",
    source:{title:"PostgreSQL range aggregation",url:"https://www.postgresql.org/docs/17/functions-aggregate.html"},
    scenario:"Busy periods are [9, 11), [10, 12), and [14, 15). The end time is excluded.",
    frames:["Begin with the occupied period [9, 11).","[10, 12) overlaps it. Extend the end to 12.","[14, 15) is separate. The union is [9, 12) and [14, 15)."],
    question:"Why does the merged first interval end at 12?",options:["Always add the end times","Use the latest end among overlaps","Keep the first booking unchanged"],correct:1,
    feedback:["End times are positions, not durations to add.","Yes. The union must cover every occupied instant.","That would omit the occupied time from 11 to 12."],
    reflection:"Why should a cancellation update the original bookings before recomputing this summary?",practice:"range-ledger",
  },
  {
    id:"linked-list-reversal",product:"GLib: reversing a linked collection",evidence:"Documented implementation",
    use:"GLib's g_list_reverse reverses a doubly linked list by switching each element's next and previous pointers.",
    mechanism:"Rewire links rather than copying payloads. Keep enough traversal state to reach the next unprocessed node and return the new head.",
    tradeoff:"Mutating a shared list affects other holders of its nodes. Arrays are usually simpler when indexed access is needed; list reversal is not how every undo feature works.",
    source:{title:"GLib g_list_reverse",url:"https://docs.gtk.org/glib/type_func.List.reverse.html"},
    scenario:"For a simpler singly linked list A → B → C, reverse the direction without losing access to B.",
    frames:["Save B before changing A.next. Set A.next to empty.","Save C before changing B.next. Point B.next to A.","Point C.next to B. Return C as the new head: C → B → A."],
    question:"What must you save before changing A.next?",options:["Only the value in A","The link to B","The list length"],correct:1,
    feedback:["The value alone cannot lead you to the remaining nodes.","Yes. Otherwise you may lose the path to the unprocessed list.","Length does not tell you where B is stored."],
    reflection:"Which callers might be affected if they still hold a reference to the old head?",practice:"exercism-reverse-string",
  },
  {
    id:"top-k",product:"Python heapq: selecting the largest readings",evidence:"Documented implementation",
    use:"Python exposes nlargest for selecting the largest k items. A monitoring tool can apply it to a batch of slow request durations.",
    mechanism:"A bounded min-heap can retain k candidates, with the smallest candidate available for replacement.",
    tradeoff:"For small k this can avoid a full sort. Full rankings, frequent updates or k close to the input size may favor other structures or sorting.",
    source:{title:"Python heapq selection functions",url:"https://docs.python.org/3/library/heapq.html"},
    scenario:"Keep the two slowest requests from durations [40, 10, 70, 25] milliseconds.",
    frames:["Retain 40 and 10. The smallest retained value is 10.","70 is larger than 10, so replace 10. Retain 40 and 70.","25 is smaller than 40. Ignore it. The slowest two are 70 and 40."],
    question:"When 70 arrives, which retained value should leave?",options:["40","10","Neither; keep everything"],correct:1,
    feedback:["That would lose a value larger than 10.","Yes. Evict the weakest candidate among the current top two.","That would abandon the bounded two-candidate state."],
    reflection:"Why might a live leaderboard with changing scores need more than this batch selection?",practice:"largest-step",
  },
  {
    id:"subsets",product:"Testing combinations of product features",evidence:"Illustrative product design",
    use:"A test tool can enumerate enabled/disabled feature combinations. Python itertools supplies combinatorial iterators for building such tooling.",
    mechanism:"For each feature, branch into include and exclude. Each path describes one configuration.",
    tradeoff:"n independent switches create 2^n configurations. Exhaustive testing becomes expensive; constrained or pairwise coverage answers a different, smaller testing goal.",
    source:{title:"Python itertools combinatorial iterators",url:"https://docs.python.org/3/library/itertools.html"},
    scenario:"A product has two independent switches: dark theme and email alerts.",
    frames:["Start with neither switch enabled: {}.","Consider dark theme: {} and {dark}.","Add an alerts choice to each: {}, {dark}, {alerts}, {dark, alerts}."],
    question:"How many configurations do two independent on/off switches create?",options:["2","3","4"],correct:2,
    feedback:["Each switch has two states, and their choices combine.","Remember the configuration where both are enabled.","Yes. Two choices multiplied by two choices gives four."],
    reflection:"If you add ten more switches, is exhaustive testing still a good default?",practice:"stable-guest-list",
  },
  {
    id:"topological-sort",product:"Python graphlib: scheduling dependent tasks",evidence:"Documented implementation",
    use:"TopologicalSorter exposes tasks whose prerequisites are complete, allowing a scheduler to run independent tasks concurrently.",
    mechanism:"Start with nodes that have no unmet prerequisites. Finishing a task can make its dependents ready.",
    tradeoff:"A cycle prevents a complete dependency order. The ordering alone does not handle failed jobs, resource limits or retries.",
    source:{title:"Python graphlib TopologicalSorter",url:"https://docs.python.org/3/library/graphlib.html"},
    scenario:"A delivery pipeline must compile before testing, and test before deploying. Lint has no dependency.",
    frames:["Compile and lint are initially ready. Either may start.","Once compile finishes, test becomes ready.","Once test finishes, deploy becomes ready. Lint's position can vary."],
    question:"Which tasks may start before any other task finishes?",options:["Deploy and test","Compile and lint","Only deploy"],correct:1,
    feedback:["Both still have unfinished prerequisites.","Yes. They have no unmet prerequisite in this example.","Deploy must wait for the test."],
    reflection:"What should the scheduler do when compilation fails rather than finishes successfully?",practice:"reachable-stations",
  },
  {
    id:"k-way-merge",product:"Python heapq: combining sorted logs",evidence:"Documented implementation",
    use:"Python's heapq.merge combines sorted inputs lazily; its documentation gives merging timestamped log files as an example.",
    mechanism:"Compare the next available item from each stream. Emit the smallest, then advance only that stream.",
    tradeoff:"Every input must already be sorted. Clock skew affects what timestamps mean; this merge does not establish causal order across servers.",
    source:{title:"Python heapq.merge",url:"https://docs.python.org/3/library/heapq.html#heapq.merge"},
    scenario:"Three log streams contain times [1, 8], [2, 6], and [3, 4].",
    frames:["The stream heads are 1, 2, 3. Emit 1; expose 8 from its stream.","The heads are 8, 2, 3. Emit 2; expose 6.","Continue with 3, 4, 6, 8. The result is 1, 2, 3, 4, 6, 8."],
    question:"After emitting 1, which stream should advance?",options:["All streams","Only the stream that supplied 1","None"],correct:1,
    feedback:["Advancing every stream would discard unconsumed entries.","Yes. The other heads still need to be considered.","Without advancing, the same item would be emitted again."],
    reflection:"What could go wrong if one server's clock is five minutes behind?",practice:"largest-step",
  },
  {
    id:"backtracking",product:"pip: resolving package dependencies",evidence:"Documented implementation",
    use:"pip backtracks over package-version choices when dependencies conflict. A version that looked promising may need to be reconsidered.",
    mechanism:"Choose a candidate, propagate its constraints, and undo the choice if no compatible continuation exists.",
    tradeoff:"Exploring many candidate versions can be slow. Useful version constraints reduce search, but overconstraining can make the request impossible.",
    source:{title:"pip dependency resolution and backtracking",url:"https://pip.pypa.io/en/stable/topics/dependency-resolution/"},
    scenario:"Your app requires library X version 1. Plugin P version 2 requires X version 2; P version 1 accepts X version 1.",
    frames:["Try P version 2. Its requirement conflicts with the app's X version 1.","Undo that candidate rather than changing the app's requirement silently.","Try P version 1. The requirements now agree on X version 1."],
    question:"What should the resolver do after the first conflict?",options:["Ignore the app's requirement","Reconsider the plugin version","Declare every version impossible"],correct:1,
    feedback:["That would violate the requested environment.","Yes. A failed branch does not rule out the remaining candidates.","Only the current candidate has been disproved."],
    reflection:"How could an unnecessary exact version pin remove a valid solution?",practice:"fewest-tokens",
  },
  {
    id:"two-heaps",product:"Designing an exact median dashboard",evidence:"Illustrative product design",
    use:"A small dashboard could maintain an exact median of incoming measurements with two heaps. This is a design exercise, not a claim about Prometheus internals.",
    mechanism:"Keep the lower half in a max-heap and the upper half in a min-heap. Balance their sizes; the middle value lies at the roots.",
    tradeoff:"Keeping all values costs growing memory; expiring old values needs extra machinery. Production monitoring often uses histograms or streaming quantile estimates instead.",
    source:{title:"Prometheus: histogram and summary tradeoffs",url:"https://prometheus.io/docs/practices/histograms/"},
    scenario:"Latencies arrive as 2, 10, 4 milliseconds. Maintain the median of all readings so far.",
    frames:["After 2: lower half [2], upper half empty. Median 2.","After 10: lower [2], upper [10]. Median (2 + 10) / 2 = 6.","After 4 and rebalancing: lower [2, 4], upper [10]. Median 4. These are sorted views of the heap contents."],
    question:"Why is the final median 4 rather than the average of all three values?",options:["Median is the middle ordered value","Median always means the newest value","Median and average are identical"],correct:0,
    feedback:["Yes. Ordering gives 2, 4, 10, whose middle value is 4.","The newest value happens to be the middle here; that is not the rule.","The mean and median describe different summaries."],
    reflection:"What changes if the dashboard needs only the last hour of readings?",practice:"largest-step",
  },
  {
    id:"knapsack",product:"Google OR-Tools: selecting under capacity",evidence:"Documented implementation",
    use:"OR-Tools provides a knapsack solver for choosing valuable items subject to capacity limits.",
    mechanism:"For a simple integer-capacity teaching model, compare skipping an item with taking it if it fits. Reuse answers for smaller item prefixes and capacities.",
    tradeoff:"The classic dynamic program costs O(n × capacity), so large numeric capacities matter. OR-Tools has specialized solvers; this lesson does not claim they all use this recurrence.",
    source:{title:"OR-Tools knapsack guide",url:"https://developers.google.com/optimization/pack/knapsack"},
    scenario:"A download budget is 5 MB. Optional files A, B, C cost 3, 2, 4 MB and have usefulness scores 5, 4, 6. Each can be selected once.",
    frames:["Choosing only C uses 4 MB for a score of 6.","Choosing A and B uses exactly 5 MB for a score of 9.","A + C and B + C exceed the budget. The best feasible choice is A + B."],
    question:"Which selection gives the greatest score within 5 MB?",options:["C alone","A and B","All three"],correct:1,
    feedback:["C has the highest individual score. Could two smaller files do better together?","Yes. They fit together and score 9.","Their combined size exceeds the budget."],
    reflection:"What extra constraint is needed if file B depends on downloading file C?",practice:"fewest-tokens",
  },
];
export function getProductLesson(id: string) { return productLessons.find(lesson => lesson.id === id); }
